// web/src/pages/Donate.tsx
import { Heart, Coffee, Gift, Github, CreditCard, ExternalLink } from "lucide-react";
import { useTranslation } from "react-i18next";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "../components/ui/card";
import { Button } from "../components/ui/button";
import { useDocumentTitle } from "../hooks/useDocumentTitle";

interface DonationPlatform {
  /** i18n key suffix under `donate.platform.*` for label/desc. */
  key: "github" | "kofi" | "bmc" | "patreon" | "paypal";
  href: string;
  icon: React.ComponentType<{ className?: string }>;
  /** Tailwind classes for accent ring + icon tint. */
  accent: string;
}

const PLATFORMS: DonationPlatform[] = [
  {
    key: "github",
    href: "https://github.com/sponsors/poli0981",
    icon: Github,
    accent: "ring-violet-500/30 text-violet-400",
  },
  {
    key: "kofi",
    href: "https://ko-fi.com/skullmute",
    icon: Coffee,
    accent: "ring-rose-500/30 text-rose-400",
  },
  {
    key: "bmc",
    href: "https://buymeacoffee.com/skullmute",
    icon: Coffee,
    accent: "ring-amber-500/30 text-amber-400",
  },
  {
    key: "patreon",
    href: "https://patreon.com/skullmute",
    icon: Gift,
    accent: "ring-orange-500/30 text-orange-400",
  },
  {
    key: "paypal",
    href: "https://paypal.me/DungDang212",
    icon: CreditCard,
    accent: "ring-blue-500/30 text-blue-400",
  },
];

export function DonatePage() {
  const { t } = useTranslation();
  useDocumentTitle("donate.title");
  return (
    <div className="max-w-3xl space-y-6">
      <div>
        <h1 className="flex items-center gap-2 text-2xl font-semibold tracking-tight">
          <Heart className="h-6 w-6 text-rose-400" /> {t("donate.title")}
        </h1>
        <p className="text-sm text-muted-foreground">{t("donate.subtitle")}</p>
      </div>

      <div className="grid gap-3 sm:grid-cols-2">
        {PLATFORMS.map((p) => (
          <Card key={p.key} className="flex flex-col">
            <CardHeader className="pb-3">
              <CardTitle className="flex items-center gap-2 text-base">
                <span
                  className={`grid h-9 w-9 place-items-center rounded-md bg-card ring-1 ${p.accent}`}
                >
                  <p.icon className="h-4 w-4" />
                </span>
                {t(`donate.platform.${p.key}`)}
              </CardTitle>
              <CardDescription className="text-xs">
                {t(`donate.platform.${p.key}Desc`)}
              </CardDescription>
            </CardHeader>
            <CardContent className="mt-auto">
              <Button asChild variant="outline" size="sm" className="w-full">
                <a href={p.href} target="_blank" rel="noopener noreferrer">
                  <ExternalLink className="mr-1 h-3 w-3" /> {t("donate.cta")}
                </a>
              </Button>
            </CardContent>
          </Card>
        ))}
      </div>

      <p className="text-xs text-muted-foreground">{t("donate.footnote")}</p>
    </div>
  );
}

// web/src/routes/donate/+page.svelte
<script lang="ts">
  import type { Component } from "svelte";
  import Heart from "@lucide/svelte/icons/heart";
  import Coffee from "@lucide/svelte/icons/coffee";
  import Gift from "@lucide/svelte/icons/gift";
  import Github from "@lucide/svelte/icons/git-branch";
  import CreditCard from "@lucide/svelte/icons/credit-card";
  import ExternalLink from "@lucide/svelte/icons/external-link";
  import { i18n } from "$lib/i18n.svelte";
  import PageHeader from "$lib/common/PageHeader.svelte";
  import Seo from "$lib/common/Seo.svelte";

  const t = i18n.t;

  // Donation links, NOT contact channels - the contact list collapsed to
  // poli0981.dev/links/, these did not. They are separate surfaces with
  // separate URLs and belong here.
  const PLATFORMS: { key: string; href: string; icon: Component<{ class?: string }> }[] = [
    { key: "github", href: "https://github.com/sponsors/poli0981", icon: Github },
    { key: "kofi", href: "https://ko-fi.com/skullmute", icon: Coffee },
    { key: "bmc", href: "https://buymeacoffee.com/skullmute", icon: Coffee },
    { key: "patreon", href: "https://patreon.com/skullmute", icon: Gift },
    { key: "paypal", href: "https://paypal.me/DungDang212", icon: CreditCard },
  ];
</script>

<Seo title={t("donate.title")} description={t("donate.subtitle")} />

<PageHeader title={t("donate.title")} />

<div class="max-w-2xl space-y-4">
  <div class="flex items-start gap-3 rounded-lg border border-primary/30 bg-primary/5 p-5">
    <Heart class="mt-0.5 size-5 shrink-0 text-primary" />
    <p class="text-sm text-muted-foreground">{t("donate.subtitle")}</p>
  </div>

  <div class="grid gap-2 sm:grid-cols-2">
    {#each PLATFORMS as p (p.key)}
      <a
        href={p.href}
        target="_blank"
        rel="noreferrer"
        class="group flex items-start gap-3 rounded-lg border bg-card p-4 transition-colors
               hover:border-border-strong hover:bg-accent"
      >
        <span class="grid size-9 shrink-0 place-items-center rounded-lg bg-muted text-muted-foreground">
          <p.icon class="size-4" />
        </span>
        <span class="min-w-0 flex-1">
          <span class="block font-medium">{t(`donate.platform.${p.key}`)}</span>
          <span class="mt-0.5 block text-sm text-muted-foreground">
            {t(`donate.platform.${p.key}Desc`)}
          </span>
        </span>
        <ExternalLink class="mt-0.5 size-3.5 shrink-0 text-muted-foreground" />
      </a>
    {/each}
  </div>

  <p class="text-sm text-muted-foreground">{t("donate.footnote")}</p>
</div>
