// web/src/lib/games/GamesTable.svelte
<script lang="ts">
  import { createVirtualizer } from "@tanstack/svelte-virtual";
  import ExternalLink from "@lucide/svelte/icons/external-link";
  import TriangleAlert from "@lucide/svelte/icons/triangle-alert";
  import ChevronUp from "@lucide/svelte/icons/chevron-up";
  import ChevronDown from "@lucide/svelte/icons/chevron-down";
  import ChevronsUpDown from "@lucide/svelte/icons/chevrons-up-down";
  import type { GameRecord } from "../schema";
  import { COLS, TOTAL_WIDTH, reviewTone } from "./columns";
  import { filters } from "../filters.svelte";
  import { i18n } from "../i18n.svelte";
  import { appidOf } from "../data-store";
  import { headerToCapsule } from "../image";
  import { recordIssues } from "../validation";
  import { formatNumber, parseReviewPercent, cn } from "../utils";
  import Badge from "../ui/Badge.svelte";

  let { rows }: { rows: GameRecord[] } = $props();

  const t = i18n.t;

  let viewport: HTMLDivElement | undefined = $state();

  // 44px rows, overscan 12 - carried over. Overscan matters on a fast scroll:
  // too low and rows paint blank, too high and the virtualiser stops earning
  // its keep.
  // $derived.by, and it READS `viewport` in the body.
  //
  // getScrollElement is a closure, so referencing `viewport` only inside it
  // does not register a dependency: the virtualizer was built once, before
  // bind:this had run, measured a null scroll element, and never rebuilt. The
  // symptom is subtle - getTotalSize() still returns the right height, so the
  // scrollbar looks correct, while getVirtualItems() returns nothing and every
  // row is blank.
  const virtualizer = $derived.by(() => {
    const el = viewport;
    return createVirtualizer<HTMLDivElement, HTMLDivElement>({
      count: rows.length,
      getScrollElement: () => el ?? null,
      estimateSize: () => 44,
      overscan: 12,
    });
  });

  const items = $derived($virtualizer.getVirtualItems());

  function toggleSort(key: string, sortable?: boolean) {
    if (!sortable) return;
    if (filters.sortKey !== key) {
      filters.sortKey = key;
      filters.sortDir = "asc";
    } else if (filters.sortDir === "asc") {
      filters.sortDir = "desc";
    } else {
      // Third click clears, rather than cycling back to asc: there is no other
      // way to get back to the natural order once you have sorted.
      filters.sortKey = null;
      filters.sortDir = null;
    }
  }
</script>

<div class="overflow-hidden rounded-lg border bg-card">
  <div bind:this={viewport} class="h-[calc(100dvh-20rem)] overflow-auto scrollbar-thin">
    <div style:width="{TOTAL_WIDTH}px" style:min-width="100%">
      <!-- Sticky header. A real <table> cannot be virtualised without either
           losing sticky headers or fighting the row heights, so this is a grid
           that keeps the table SEMANTICS through role attributes. -->
      <div
        role="row"
        class="sticky top-0 z-10 flex h-10 items-center border-b bg-card/95 backdrop-blur"
      >
        {#each COLS as col (col.key)}
          {@const active = filters.sortKey === col.key}
          <div
            role="columnheader"
            aria-sort={active ? (filters.sortDir === "asc" ? "ascending" : "descending") : "none"}
            style:width="{col.width}px"
            class="shrink-0 px-2"
          >
            {#if col.label}
              <button
                type="button"
                disabled={!col.sortable}
                onclick={() => toggleSort(col.key, col.sortable)}
                title={col.sortable ? t("games.sortBy", { column: t(col.label) }) : undefined}
                class={cn(
                  "flex w-full items-center gap-1 text-xs font-semibold uppercase tracking-wide",
                  col.align === "right" && "justify-end",
                  col.sortable ? "hover:text-foreground" : "cursor-default",
                  active ? "text-foreground" : "text-muted-foreground",
                )}
              >
                <span class="truncate">{t(col.label)}</span>
                {#if col.sortable}
                  {#if !active}
                    <ChevronsUpDown class="size-3 shrink-0 opacity-40" />
                  {:else if filters.sortDir === "asc"}
                    <ChevronUp class="size-3 shrink-0" />
                  {:else}
                    <ChevronDown class="size-3 shrink-0" />
                  {/if}
                {/if}
              </button>
            {/if}
          </div>
        {/each}
      </div>

      <div style:height="{$virtualizer.getTotalSize()}px" class="relative">
        {#each items as item (item.key)}
          {@const g = rows[item.index]}
          {@const appid = appidOf(g)}
          {@const issues = recordIssues(g)}
          {@const pct = parseReviewPercent(g.reviews)}
          <a
            href={appid ? `/games/${appid}` : g.link}
            role="row"
            class="absolute left-0 flex items-center border-b text-sm transition-colors hover:bg-accent/60"
            style:height="{item.size}px"
            style:width="{TOTAL_WIDTH}px"
            style:transform="translateY({item.start}px)"
          >
            {#each COLS as col (col.key)}
              <div
                role="cell"
                style:width="{col.width}px"
                class={cn(
                  "shrink-0 truncate px-2",
                  col.align === "right" && "text-right",
                )}
              >
                {#if col.key === "thumb"}
                  {#if g.header_image}
                    <img
                      src={headerToCapsule(g.header_image)}
                      alt=""
                      loading="lazy"
                      decoding="async"
                      width="92"
                      height="43"
                      class="h-8 w-14 rounded object-cover"
                    />
                  {:else}
                    <div class="h-8 w-14 rounded bg-muted"></div>
                  {/if}
                {:else if col.key === "issues"}
                  {#if issues.length}
                    <span
                      class="grid size-5 place-items-center text-warning"
                      title={issues.map((i) => i.label).join(" · ")}
                    >
                      <TriangleAlert class="size-3.5" />
                    </span>
                  {/if}
                {:else if col.key === "name"}
                  <span class="font-medium">
                    {#if g.is_dead}<span title={t("games.deadTitle")} class="mr-1">💀</span>{/if}
                    {g.name || "—"}
                  </span>
                {:else if col.key === "genre"}
                  {#if g.genre}<Badge variant="outline">{g.genre}</Badge>{:else}<span class="text-muted-foreground">—</span>{/if}
                {:else if col.key === "type_game"}
                  {#if g.type_game}
                    <Badge variant={g.type_game === "online" ? "success" : "secondary"}>
                      {t(g.type_game === "online" ? "common.online" : "common.offline")}
                    </Badge>
                  {:else}<span class="text-muted-foreground">—</span>{/if}
                {:else if col.key === "reviews"}
                  {#if pct === null}
                    <span class="text-muted-foreground">—</span>
                  {:else}
                    <span class={cn("font-mono tnum", reviewTone(pct))}>{pct}%</span>
                  {/if}
                {:else if col.key === "current_players"}
                  <span class="font-mono tnum">{formatNumber(g.current_players)}</span>
                {:else if col.key === "anti_cheat"}
                  {#if g.anti_cheat && g.anti_cheat !== "-"}
                    <Badge variant={g.is_kernel_ac ? "destructive" : "warning"}>{g.anti_cheat}</Badge>
                  {:else}<span class="text-muted-foreground">—</span>{/if}
                {:else if col.key === "platforms"}
                  <span class="text-xs text-muted-foreground">
                    {(g.platforms ?? []).join(", ") || "—"}
                  </span>
                {:else if col.key === "release_date"}
                  <span class="text-xs text-muted-foreground">{g.release_date || "—"}</span>
                {:else if col.key === "status"}
                  <Badge variant={g.status === "active" ? "secondary" : "destructive"}>
                    {t(g.status === "active" ? "common.active" : "common.delisted")}
                  </Badge>
                {:else if col.key === "link"}
                  <!-- stopPropagation so the Steam link does not also trigger
                       the row navigation wrapping it. -->
                  <span
                    role="link"
                    tabindex="0"
                    title={t("detail.openOnSteam", { appid: appidOf(g) })}
                    onclick={(e) => {
                      e.preventDefault();
                      e.stopPropagation();
                      window.open(g.link, "_blank", "noopener,noreferrer");
                    }}
                    onkeydown={(e) => {
                      if (e.key === "Enter") {
                        e.preventDefault();
                        e.stopPropagation();
                        window.open(g.link, "_blank", "noopener,noreferrer");
                      }
                    }}
                    class="inline-grid size-6 place-items-center text-muted-foreground hover:text-primary"
                  >
                    <ExternalLink class="size-3.5" />
                  </span>
                {/if}
              </div>
            {/each}
          </a>
        {/each}
      </div>
    </div>
  </div>
</div>

// web/src/components/games/GamesTable.tsx
import { useMemo, useRef, useState } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import Fuse from "fuse.js";
import { ArrowUp, ArrowDown, ExternalLink } from "lucide-react";
import { Badge } from "../ui/badge";
import { useFilters } from "../../stores/filters";
import { formatNumber, parseIntSafe, parseReviewPercent } from "../../lib/utils";
import { extractAppid } from "../../lib/data-store";
import type { GameRecord } from "../../lib/schema";
import { cn } from "../../lib/utils";
import { GameDetailDrawer } from "./GameDetailDrawer";

interface Props {
  records: GameRecord[];
}

interface ColDef {
  key: string;
  label: string;
  width: number;
  sortable?: boolean;
  align?: "left" | "right" | "center";
  render: (g: GameRecord) => React.ReactNode;
  sortValue?: (g: GameRecord) => string | number;
}

const COLS: ColDef[] = [
  {
    key: "thumb",
    label: "",
    width: 56,
    render: (g) =>
      g.header_image ? (
        <img
          loading="lazy"
          src={g.header_image}
          alt=""
          className="h-8 w-16 rounded object-cover"
        />
      ) : (
        <div className="h-8 w-16 rounded bg-muted" />
      ),
  },
  {
    key: "name",
    label: "Name",
    width: 280,
    sortable: true,
    sortValue: (g) => g.name?.toLowerCase() ?? "",
    render: (g) => <span className="font-medium">{g.name || "—"}</span>,
  },
  {
    key: "genre",
    label: "Genre",
    width: 120,
    sortable: true,
    sortValue: (g) => g.genre ?? "",
    render: (g) =>
      g.genre ? (
        <Badge variant="outline" className="font-normal">
          {g.genre}
        </Badge>
      ) : (
        "—"
      ),
  },
  {
    key: "type_game",
    label: "Type",
    width: 80,
    sortable: true,
    sortValue: (g) => g.type_game ?? "",
    render: (g) =>
      g.type_game ? (
        <Badge
          variant={g.type_game === "online" ? "success" : "secondary"}
          className="font-normal"
        >
          {g.type_game}
        </Badge>
      ) : (
        "—"
      ),
  },
  {
    key: "reviews",
    label: "Reviews",
    width: 110,
    sortable: true,
    align: "right",
    sortValue: (g) => parseReviewPercent(g.reviews) ?? -1,
    render: (g) => {
      const pct = parseReviewPercent(g.reviews);
      if (pct === null) return <span className="text-muted-foreground">—</span>;
      const color =
        pct >= 80 ? "text-emerald-400" : pct >= 70 ? "text-amber-400" : "text-rose-400";
      return <span className={cn("font-mono", color)}>{pct}%</span>;
    },
  },
  {
    key: "current_players",
    label: "Players",
    width: 110,
    sortable: true,
    align: "right",
    sortValue: (g) => parseIntSafe(g.current_players),
    render: (g) => (
      <span className="font-mono">{formatNumber(g.current_players)}</span>
    ),
  },
  {
    key: "anti_cheat",
    label: "AC",
    width: 100,
    sortable: true,
    sortValue: (g) => g.anti_cheat ?? "",
    render: (g) =>
      g.anti_cheat && g.anti_cheat !== "-" ? (
        <Badge
          variant={g.is_kernel_ac ? "destructive" : "warning"}
          className="font-normal"
        >
          {g.anti_cheat}
        </Badge>
      ) : (
        <span className="text-muted-foreground">—</span>
      ),
  },
  {
    key: "platforms",
    label: "Platforms",
    width: 140,
    render: (g) => (
      <span className="text-xs text-muted-foreground">
        {(g.platforms ?? []).join(", ") || "—"}
      </span>
    ),
  },
  {
    key: "release_date",
    label: "Released",
    width: 120,
    sortable: true,
    sortValue: (g) => g.release_date ?? "",
    render: (g) => (
      <span className="text-xs text-muted-foreground">{g.release_date || "—"}</span>
    ),
  },
  {
    key: "status",
    label: "Status",
    width: 90,
    sortable: true,
    sortValue: (g) => g.status ?? "",
    render: (g) => (
      <Badge
        variant={g.status === "active" ? "secondary" : "destructive"}
        className="font-normal"
      >
        {g.status}
      </Badge>
    ),
  },
  {
    key: "link",
    label: "",
    width: 48,
    render: (g) => (
      <a
        href={g.link}
        target="_blank"
        rel="noreferrer"
        onClick={(e) => e.stopPropagation()}
        className="text-muted-foreground hover:text-primary"
        title="Open on Steam"
      >
        <ExternalLink className="h-3.5 w-3.5" />
      </a>
    ),
  },
];

const TOTAL_WIDTH = COLS.reduce((s, c) => s + c.width, 0);

export function GamesTable({ records }: Props) {
  const search = useFilters((s) => s.search);
  const genre = useFilters((s) => s.genre);
  const typeGame = useFilters((s) => s.type_game);
  const platform = useFilters((s) => s.platform);
  const status = useFilters((s) => s.status);
  const sortKey = useFilters((s) => s.sortKey);
  const sortDir = useFilters((s) => s.sortDir);
  const setSort = useFilters((s) => s.setSort);
  const [selected, setSelected] = useState<GameRecord | null>(null);

  const fuse = useMemo(
    () =>
      new Fuse(records, {
        keys: ["name", "description", "tags", "developer", "publisher"],
        threshold: 0.32,
        ignoreLocation: true,
      }),
    [records],
  );

  const filtered = useMemo(() => {
    let out = records;
    if (search.trim()) {
      out = fuse.search(search.trim()).map((r) => r.item);
    }
    if (genre) out = out.filter((g) => g.genre === genre);
    if (typeGame) out = out.filter((g) => g.type_game === typeGame);
    if (platform)
      out = out.filter((g) => (g.platforms ?? []).includes(platform));
    if (status) out = out.filter((g) => g.status === status);
    return out;
  }, [records, search, genre, typeGame, platform, status, fuse]);

  const sorted = useMemo(() => {
    if (!sortKey || !sortDir) return filtered;
    const col = COLS.find((c) => c.key === sortKey);
    if (!col?.sortValue) return filtered;
    const sv = col.sortValue;
    const arr = [...filtered];
    arr.sort((a, b) => {
      const va = sv(a);
      const vb = sv(b);
      if (va < vb) return sortDir === "asc" ? -1 : 1;
      if (va > vb) return sortDir === "asc" ? 1 : -1;
      return 0;
    });
    return arr;
  }, [filtered, sortKey, sortDir]);

  const containerRef = useRef<HTMLDivElement>(null);
  const rowVirtualizer = useVirtualizer({
    count: sorted.length,
    getScrollElement: () => containerRef.current,
    estimateSize: () => 44,
    overscan: 12,
  });

  function toggleSort(key: string) {
    if (sortKey !== key) return setSort(key, "desc");
    if (sortDir === "desc") return setSort(key, "asc");
    return setSort(null, null);
  }

  return (
    <div className="rounded-lg border bg-card">
      <div className="flex items-center justify-between border-b px-3 py-2 text-xs text-muted-foreground">
        <span>
          <strong className="text-foreground">{formatNumber(sorted.length)}</strong>{" "}
          of {formatNumber(records.length)} games
        </span>
      </div>

      <div
        ref={containerRef}
        className="relative h-[calc(100vh-260px)] overflow-auto scrollbar-thin"
      >
        <div style={{ width: TOTAL_WIDTH, minWidth: "100%" }}>
          {/* Header */}
          <div className="sticky top-0 z-10 flex border-b bg-card/95 backdrop-blur">
            {COLS.map((c) => {
              const active = sortKey === c.key;
              return (
                <div
                  key={c.key}
                  className={cn(
                    "flex h-10 items-center px-3 text-xs font-semibold uppercase tracking-wider text-muted-foreground",
                    c.align === "right" && "justify-end",
                    c.align === "center" && "justify-center",
                    c.sortable && "cursor-pointer select-none hover:text-foreground",
                  )}
                  style={{ width: c.width, minWidth: c.width }}
                  onClick={() => c.sortable && toggleSort(c.key)}
                >
                  <span>{c.label}</span>
                  {c.sortable && active && (
                    <span className="ml-1 inline-flex">
                      {sortDir === "asc" ? (
                        <ArrowUp className="h-3 w-3" />
                      ) : (
                        <ArrowDown className="h-3 w-3" />
                      )}
                    </span>
                  )}
                </div>
              );
            })}
          </div>

          {/* Virtual rows */}
          <div
            style={{
              height: rowVirtualizer.getTotalSize(),
              width: "100%",
              position: "relative",
            }}
          >
            {rowVirtualizer.getVirtualItems().map((vrow) => {
              const g = sorted[vrow.index];
              return (
                <div
                  key={vrow.key}
                  className="absolute left-0 top-0 flex w-full cursor-pointer items-center border-b border-border/50 hover:bg-accent/40"
                  style={{
                    transform: `translateY(${vrow.start}px)`,
                    height: vrow.size,
                  }}
                  onClick={() => setSelected(g)}
                  data-appid={extractAppid(g.link)}
                >
                  {COLS.map((c) => (
                    <div
                      key={c.key}
                      className={cn(
                        "flex items-center px-3 py-2 text-sm",
                        c.align === "right" && "justify-end",
                        c.align === "center" && "justify-center",
                      )}
                      style={{ width: c.width, minWidth: c.width }}
                    >
                      {c.render(g)}
                    </div>
                  ))}
                </div>
              );
            })}
          </div>
        </div>
      </div>

      <GameDetailDrawer game={selected} onClose={() => setSelected(null)} />
    </div>
  );
}
