// web/src/components/layout/Topbar.tsx
import { Search, Sun, Moon, Monitor, Menu, Command } from "lucide-react";
import { useEffect, useState } from "react";
import { useTranslation } from "react-i18next";
import { Input } from "../ui/input";
import { Button } from "../ui/button";
import { PwaIndicator } from "../common/PwaIndicator";
import { openCommandPalette } from "../common/CommandPalette";
import { useFilters } from "../../stores/filters";
import { useGames } from "../../hooks/useGames";
import { formatNumber } from "../../lib/utils";

type Theme = "light" | "dark" | "system";

function applyTheme(t: Theme) {
  const root = document.documentElement;
  root.classList.remove("dark", "light");
  if (t === "system") {
    const prefers = window.matchMedia("(prefers-color-scheme: dark)").matches;
    root.classList.add(prefers ? "dark" : "light");
  } else {
    root.classList.add(t);
  }
}

interface TopbarProps {
  /** Hamburger handler — only shown on viewports without the desktop sidebar. */
  onMenuToggle?: () => void;
}

export function Topbar({ onMenuToggle }: TopbarProps = {}) {
  const { t } = useTranslation();
  const search = useFilters((s) => s.search);
  const setSearch = useFilters((s) => s.setSearch);
  const games = useGames();
  const [theme, setTheme] = useState<Theme>(
    (localStorage.getItem("f2p:theme") as Theme) ?? "dark",
  );

  useEffect(() => {
    applyTheme(theme);
    localStorage.setItem("f2p:theme", theme);
  }, [theme]);

  const total = games.data?.records.length ?? 0;
  const lastUpdated = games.data?.index.last_updated ?? "";

  return (
    <header className="sticky top-0 z-30 flex h-14 items-center gap-3 border-b bg-background/95 px-4 backdrop-blur supports-[backdrop-filter]:bg-background/70">
      <Button
        variant="ghost"
        size="icon"
        aria-label={t("topbar.menuOpen")}
        className="-ml-2 lg:hidden"
        onClick={onMenuToggle}
      >
        <Menu className="h-4 w-4" />
      </Button>

      <div className="relative flex-1 max-w-xl">
        <Search className="pointer-events-none absolute left-2.5 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
        <Input
          placeholder={t("topbar.searchPlaceholder")}
          value={search}
          onChange={(e) => setSearch(e.target.value)}
          className="pl-8 pr-14"
        />
        <kbd className="pointer-events-none absolute right-2 top-1/2 hidden h-5 -translate-y-1/2 select-none items-center rounded border bg-muted px-1.5 font-mono text-[10px] text-muted-foreground md:inline-flex">
          ⌘K
        </kbd>
        {/* Touch equivalent of ⌘K — the soft keyboard can't send the chord. */}
        <button
          type="button"
          aria-label={t("cmdk.placeholder")}
          onClick={openCommandPalette}
          className="absolute right-1.5 top-1/2 inline-flex h-7 w-7 -translate-y-1/2 items-center justify-center rounded text-muted-foreground hover:text-foreground md:hidden"
        >
          <Command className="h-4 w-4" />
        </button>
      </div>

      <div className="hidden items-center gap-3 text-xs text-muted-foreground md:flex">
        <span
          dangerouslySetInnerHTML={{
            __html: t("topbar.gamesCount", { count: total }).replace(
              String(total),
              `<strong class="text-foreground">${formatNumber(total)}</strong>`,
            ),
          }}
        />
        {lastUpdated && (
          <span title={lastUpdated}>
            {t("topbar.updated", { date: lastUpdated.slice(0, 10) })}
          </span>
        )}
      </div>

      <PwaIndicator />

      <div className="flex items-center gap-1">
        <Button
          variant="ghost"
          size="icon"
          aria-label={t("system.themeLight")}
          onClick={() => setTheme("light")}
          className={theme === "light" ? "text-foreground" : "text-muted-foreground"}
        >
          <Sun className="h-4 w-4" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          aria-label={t("system.themeDark")}
          onClick={() => setTheme("dark")}
          className={theme === "dark" ? "text-foreground" : "text-muted-foreground"}
        >
          <Moon className="h-4 w-4" />
        </Button>
        <Button
          variant="ghost"
          size="icon"
          aria-label={t("system.themeSystem")}
          onClick={() => setTheme("system")}
          className={theme === "system" ? "text-foreground" : "text-muted-foreground"}
        >
          <Monitor className="h-4 w-4" />
        </Button>
      </div>
    </header>
  );
}

// web/src/lib/layout/Topbar.svelte
<script lang="ts">
  import Menu from "@lucide/svelte/icons/menu";
  import Search from "@lucide/svelte/icons/search";
  import Sun from "@lucide/svelte/icons/sun";
  import Moon from "@lucide/svelte/icons/moon";
  import Monitor from "@lucide/svelte/icons/monitor";
  import { goto } from "$app/navigation";
  import { filters } from "../filters.svelte";
  import { games } from "../games.svelte";
  import { i18n } from "../i18n.svelte";
  import { theme, type Theme } from "../prefs.svelte";
  import { openPalette } from "../palette.svelte";
  import { formatNumber } from "../utils";
  import { cn } from "../utils";

  let { onOpenMenu }: { onOpenMenu: () => void } = $props();

  const t = i18n.t;

  const total = $derived(games.data?.records.length ?? 0);
  const lastUpdated = $derived(games.data?.index.last_updated ?? "");

  const THEMES: { value: Theme; icon: typeof Sun; label: string }[] = [
    { value: "light", icon: Sun, label: "settings.themeLight" },
    { value: "dark", icon: Moon, label: "settings.themeDark" },
    { value: "system", icon: Monitor, label: "settings.themeSystem" },
  ];

  // Typing in the header search jumps to /games, because the box filters the
  // table and staying on /charts while it silently filtered a table you cannot
  // see is the kind of thing that reads as a broken search.
  function onSearchInput() {
    if (filters.search && !location.pathname.startsWith("/games")) void goto("/games");
  }
</script>

<header
  class="sticky top-0 z-30 flex h-14 items-center gap-2 border-b bg-background/85 px-3 backdrop-blur-md sm:px-4"
>
  <button
    type="button"
    class="grid size-9 shrink-0 place-items-center rounded-md text-muted-foreground hover:bg-accent hover:text-foreground lg:hidden"
    onclick={onOpenMenu}
    aria-label={t("nav.menu")}
  >
    <Menu class="size-5" />
  </button>

  <div class="relative min-w-0 flex-1 sm:max-w-md">
    <Search
      class="pointer-events-none absolute left-2.5 top-1/2 size-4 -translate-y-1/2 text-muted-foreground"
    />
    <input
      type="search"
      bind:value={filters.search}
      oninput={onSearchInput}
      placeholder={t("topbar.searchPlaceholder")}
      aria-label={t("topbar.searchPlaceholder")}
      class="h-9 w-full rounded-md border border-input bg-transparent pl-8 pr-16 text-sm
             placeholder:text-muted-foreground"
    />
    <button
      type="button"
      onclick={openPalette}
      class="absolute right-1.5 top-1/2 hidden -translate-y-1/2 rounded border bg-muted px-1.5 py-0.5
             font-mono text-[10px] text-muted-foreground hover:text-foreground sm:block"
      aria-label={t("cmdk.open")}
    >
      Ctrl K
    </button>
  </div>

  {#if total}
    <p class="ml-auto hidden truncate text-xs text-muted-foreground xl:block">
      <span class="font-medium text-foreground tnum">{formatNumber(total)}</span>
      {t("topbar.gamesTracked")}
      {#if lastUpdated}
        · <span class="tnum">{lastUpdated.slice(0, 10)}</span>
      {/if}
    </p>
  {/if}

  <div
    class={cn("flex items-center gap-0.5 rounded-md border p-0.5", total ? "" : "ml-auto")}
    role="group"
    aria-label={t("settings.theme")}
  >
    {#each THEMES as option (option.value)}
      <button
        type="button"
        onclick={() => theme.set(option.value)}
        aria-pressed={theme.value === option.value}
        title={t(option.label)}
        aria-label={t(option.label)}
        class={cn(
          "grid size-7 place-items-center rounded transition-colors",
          theme.value === option.value
            ? "bg-primary/15 text-primary"
            : "text-muted-foreground hover:bg-accent hover:text-foreground",
        )}
      >
        <option.icon class="size-4" />
      </button>
    {/each}
  </div>
</header>
