// web/src/pages/Activity.tsx
import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { useTranslation } from "react-i18next";
import {
  ShieldCheck,
  ShieldAlert,
  ExternalLink,
  GitCommit,
  Bot,
  User,
  Filter,
} from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { LoadingState, ErrorState } from "../components/common/QueryState";
import { useDocumentTitle } from "../hooks/useDocumentTitle";
import { DEFAULT_BRANCH } from "../lib/schema";
import { API_ORIGIN } from "../lib/site";
import { formatRelativeDate } from "../lib/utils";
import { cn } from "../lib/utils";

/**
 * Flattened by the Worker, not by GitHub. /api/activity narrows the upstream
 * payload to these fields, so the commit-author email GitHub returns for every
 * commit never reaches the browser at all, `subject` is the first line only
 * (the bodies carry Co-Authored-By trailers with real addresses, and nothing
 * below renders them), and `avatar` arrives already rewritten to this site's
 * own /img/gh/ proxy.
 */
interface Commit {
  sha: string;
  html_url: string;
  subject: string;
  author_date: string;
  author_name: string;
  login: string | null;
  avatar: string | null;
  verified: boolean;
  reason: string;
}

// "mine" is gone with sign-in: with no signed-in identity there is no
// "me" to filter against.
type Filter = "all" | "bot";

/** The pipeline's own commits are authored by this account. */
const BOT_LOGIN = "github-actions[bot]";

async function fetchCommits(): Promise<Commit[]> {
  // Same-origin through the Worker. This page used to call api.github.com
  // directly, which leaked every visitor's IP to GitHub, forced
  // https://api.github.com into the site-wide connect-src, and returned avatar
  // URLs on a host no CSP here allowed - so every avatar was blocked outright.
  const res = await fetch(`${API_ORIGIN}/api/activity`);
  if (!res.ok) throw new Error(`Activity: ${res.status} ${res.statusText}`);
  const body = (await res.json()) as { commits?: Commit[] };
  return body.commits ?? [];
}

export function ActivityPage() {
  const { t } = useTranslation();
  useDocumentTitle("activity.title");
  const [filter, setFilter] = useState<Filter>("all");

  const q = useQuery({
    queryKey: ["activity"],
    queryFn: fetchCommits,
    refetchOnWindowFocus: true,
    staleTime: 60_000,
  });

  const filtered = useMemo(() => {
    if (!q.data) return [];
    return q.data.filter((c) => {
      const isBot = c.login === BOT_LOGIN;
      if (filter === "bot") return isBot;
      return true;
    });
  }, [q.data, filter]);

  if (q.isLoading) return <LoadingState />;
  if (q.error) return <ErrorState error={q.error as Error} onRetry={() => void q.refetch()} />;

  return (
    <div className="space-y-4">
      <div className="flex flex-wrap items-end justify-between gap-3">
        <div>
          <h1 className="text-2xl font-semibold tracking-tight">{t("activity.title")}</h1>
          <p className="text-sm text-muted-foreground">
            {t("activity.subtitle", { count: q.data?.length ?? 0, branch: DEFAULT_BRANCH })}
          </p>
        </div>
        <div className="flex items-center gap-1.5 rounded-md border bg-card p-1 text-xs">
          <Filter className="ml-1 h-3 w-3 text-muted-foreground" />
          {(["all", "bot"] as const).map((f) => (
            <Button
              key={f}
              size="sm"
              variant={filter === f ? "default" : "ghost"}
              className="h-6 text-xs"
              onClick={() => setFilter(f)}
            >
              {f === "bot" ? t("activity.filterBots") : t("activity.filterAll")}
            </Button>
          ))}
        </div>
      </div>

      <Card>
        <CardHeader className="pb-2">
          <CardTitle className="text-sm font-normal text-muted-foreground">
            {t("activity.showingCount", { count: filtered.length })}
          </CardTitle>
        </CardHeader>
        <CardContent className="p-0">
          <ul className="divide-y">
            {filtered.map((c) => (
              <CommitRow key={c.sha} commit={c} />
            ))}
            {filtered.length === 0 && (
              <li className="p-6 text-center text-sm text-muted-foreground">
                {t("activity.noMatches")}
              </li>
            )}
          </ul>
        </CardContent>
      </Card>
    </div>
  );
}

function CommitRow({ commit }: { commit: Commit }) {
  const { t } = useTranslation();
  const verified = commit.verified;
  const reason = commit.reason || "unsigned";
  const subject = commit.subject;
  const isBot = commit.login === BOT_LOGIN;

  return (
    <li className="flex items-start gap-3 px-4 py-3 hover:bg-accent/30">
      <div className="mt-0.5 shrink-0">
        {commit.avatar ? (
          <img
            src={`${API_ORIGIN}${commit.avatar}`}
            alt=""
            loading="lazy"
            decoding="async"
            className={cn(
              "h-7 w-7 rounded-full border",
              isBot && "ring-1 ring-amber-500/40",
            )}
          />
        ) : (
          <div className="grid h-7 w-7 place-items-center rounded-full border bg-muted">
            <GitCommit className="h-3 w-3 text-muted-foreground" />
          </div>
        )}
      </div>

      <div className="min-w-0 flex-1">
        <div className="flex items-center gap-2">
          <a
            href={commit.html_url}
            target="_blank"
            rel="noreferrer"
            className="truncate font-medium hover:text-primary"
          >
            {subject || t("activity.noMessage")}
          </a>
          <ExternalLink className="h-3 w-3 shrink-0 text-muted-foreground opacity-50" />
        </div>
        <div className="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
          {commit.login ? (
            <span className="inline-flex items-center gap-1">
              {isBot ? <Bot className="h-3 w-3" /> : <User className="h-3 w-3" />}
              {commit.login}
            </span>
          ) : (
            <span className="inline-flex items-center gap-1">
              <User className="h-3 w-3" />
              {commit.author_name}
            </span>
          )}
          <span>·</span>
          <span title={commit.author_date}>
            {formatRelativeDate(commit.author_date)}
          </span>
          <span>·</span>
          <code className="rounded bg-muted px-1 font-mono">
            {commit.sha.slice(0, 7)}
          </code>
        </div>
      </div>

      <div className="shrink-0">
        {verified ? (
          <Badge variant="success" className="font-normal">
            <ShieldCheck className="mr-1 h-3 w-3" /> {t("activity.verifiedBadge")}
          </Badge>
        ) : reason === "unsigned" ? (
          <Badge variant="secondary" className="font-normal">
            {t("activity.unsignedBadge")}
          </Badge>
        ) : (
          <Badge
            variant="warning"
            className="font-normal"
            title={t("activity.reasonPrefix", { reason })}
          >
            <ShieldAlert className="mr-1 h-3 w-3" /> {reason}
          </Badge>
        )}
      </div>
    </li>
  );
}

// web/src/routes/activity/+page.svelte
<script lang="ts">
  import ShieldCheck from "@lucide/svelte/icons/shield-check";
  import ShieldAlert from "@lucide/svelte/icons/shield-alert";
  import ExternalLink from "@lucide/svelte/icons/external-link";
  import GitCommit from "@lucide/svelte/icons/git-commit-horizontal";
  import Bot from "@lucide/svelte/icons/bot";
  import User from "@lucide/svelte/icons/user";
  import Filter from "@lucide/svelte/icons/funnel";
  import { Resource } from "$lib/resource.svelte";
  import { i18n } from "$lib/i18n.svelte";
  import { API_ORIGIN } from "$lib/site";
  import { DEFAULT_BRANCH } from "$lib/schema";
  import { formatRelativeDate, cn } from "$lib/utils";
  import QueryState from "$lib/common/QueryState.svelte";
  import PageHeader from "$lib/common/PageHeader.svelte";
  import Badge from "$lib/ui/Badge.svelte";
  import Button from "$lib/ui/Button.svelte";
  import Seo from "$lib/common/Seo.svelte";

  const t = i18n.t;

  /**
   * Flattened by the Worker, not by GitHub. /api/activity narrows the upstream
   * payload to these fields, so the commit-author email GitHub returns for
   * every commit never reaches the browser, `subject` is the first line only
   * (the bodies carry Co-Authored-By trailers with real addresses), and
   * `avatar` arrives already rewritten to this site's own /img/gh/ proxy.
   */
  interface Commit {
    sha: string;
    html_url: string;
    subject: string;
    author_date: string;
    author_name: string;
    login: string | null;
    avatar: string | null;
    verified: boolean;
    reason: string;
  }

  const BOT_LOGIN = "github-actions[bot]";

  // refetchOnFocus: the feed is the one page where coming back to the tab and
  // seeing yesterday's state would be actively misleading.
  const activity = new Resource<Commit[]>(
    async (signal) => {
      const res = await fetch(`${API_ORIGIN}/api/activity`, { signal });
      if (!res.ok) throw new Error(`Activity: ${res.status} ${res.statusText}`);
      return ((await res.json()) as { commits?: Commit[] }).commits ?? [];
    },
    { staleTime: 60_000, refetchOnFocus: true },
  );

  $effect(() => {
    void activity.load();
  });

  let filter = $state<"all" | "bot">("all");

  const commits = $derived(activity.data ?? []);
  const shown = $derived(filter === "bot" ? commits.filter((c) => c.login === BOT_LOGIN) : commits);
</script>

<Seo title={t("activity.title")} description={t("activity.subtitle", { count: commits.length, branch: DEFAULT_BRANCH })} />

<PageHeader
  title={t("activity.title")}
  subtitle={t("activity.subtitle", { count: commits.length, branch: DEFAULT_BRANCH })}
>
  {#snippet actions()}
    <div class="flex items-center gap-1 rounded-md border p-0.5 text-xs">
      <Filter class="ml-1 size-3 text-muted-foreground" />
      {#each ["all", "bot"] as const as f (f)}
        <Button
          size="sm"
          variant={filter === f ? "default" : "ghost"}
          class="h-6 text-xs"
          onclick={() => (filter = f)}
        >
          {f === "bot" ? t("activity.filterBots") : t("activity.filterAll")}
        </Button>
      {/each}
    </div>
  {/snippet}
</PageHeader>

<QueryState
  loading={activity.loading && !activity.data}
  error={activity.error}
  retry={() => activity.refetch()}
>
  <p class="mb-3 text-xs text-muted-foreground tnum">
    {t("activity.showingCount", { count: shown.length })}
  </p>

  <ul class="divide-y rounded-lg border bg-card">
    {#each shown as c (c.sha)}
      {@const isBot = c.login === BOT_LOGIN}
      <li class="flex items-start gap-3 px-4 py-3 hover:bg-accent/40">
        <div class="mt-0.5 shrink-0">
          {#if c.avatar}
            <img
              src={`${API_ORIGIN}${c.avatar}`}
              alt=""
              loading="lazy"
              decoding="async"
              class={cn("size-7 rounded-full border", isBot && "ring-1 ring-warning/40")}
            />
          {:else}
            <div class="grid size-7 place-items-center rounded-full border bg-muted">
              <GitCommit class="size-3 text-muted-foreground" />
            </div>
          {/if}
        </div>

        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-2">
            <a
              href={c.html_url}
              target="_blank"
              rel="noreferrer"
              class="truncate text-sm font-medium hover:text-primary"
            >
              {c.subject || t("activity.noMessage")}
            </a>
            <ExternalLink class="size-3 shrink-0 text-muted-foreground opacity-50" />
          </div>
          <div class="mt-0.5 flex flex-wrap items-center gap-x-2 gap-y-1 text-xs text-muted-foreground">
            <span class="inline-flex items-center gap-1">
              {#if isBot}<Bot class="size-3" />{:else}<User class="size-3" />{/if}
              {c.login || c.author_name}
            </span>
            <span aria-hidden="true">·</span>
            <span title={c.author_date}>{formatRelativeDate(c.author_date)}</span>
            <span aria-hidden="true">·</span>
            <code class="rounded bg-muted px-1 tnum">{c.sha.slice(0, 7)}</code>
          </div>
        </div>

        <div class="shrink-0">
          {#if c.verified}
            <Badge variant="success">
              <ShieldCheck class="mr-1 size-3" />
              {t("activity.verifiedBadge")}
            </Badge>
          {:else if c.reason === "unsigned"}
            <Badge variant="secondary">{t("activity.unsignedBadge")}</Badge>
          {:else}
            <Badge variant="warning" title={t("activity.reasonPrefix", { reason: c.reason })}>
              <ShieldAlert class="mr-1 size-3" />
              {c.reason}
            </Badge>
          {/if}
        </div>
      </li>
    {/each}

    {#if !shown.length}
      <li class="px-4 py-10 text-center text-sm text-muted-foreground">
        {t("activity.noMatches")}
      </li>
    {/if}
  </ul>
</QueryState>
