// web/src/components/games/table/MobileGameCards.tsx
import { useRef } from "react";
import { useVirtualizer } from "@tanstack/react-virtual";
import { useTranslation } from "react-i18next";
import { ExternalLink, AlertTriangle } from "lucide-react";
import { Badge } from "../../ui/badge";
import { cn, formatNumber, parseReviewPercent } from "../../../lib/utils";
import { extractAppid } from "../../../lib/data-store";
import { headerToCapsule } from "../../../lib/image";
import { recordIssues } from "../../../lib/validation";
import type { GameRecord } from "../../../lib/schema";

interface Props {
  records: GameRecord[];
  onOpen: (g: GameRecord) => void;
}

// Mobile-only card list. Mirrors GamesTable filtering/paging — caller passes
// the already-paged `records`. Virtualised for parity with the desktop table
// (1.2k+ records would otherwise stall scroll on touch devices).
export function MobileGameCards({ records, onOpen }: Props) {
  const { t } = useTranslation();
  const containerRef = useRef<HTMLDivElement>(null);
  const virtualizer = useVirtualizer({
    count: records.length,
    getScrollElement: () => containerRef.current,
    estimateSize: () => 96, // card height incl. padding + border
    overscan: 8,
  });

  return (
    <div
      ref={containerRef}
      className="relative h-[calc(100vh-260px)] overflow-auto [&::-webkit-scrollbar]:hidden [scrollbar-width:none]"
    >
      <div
        style={{
          height: virtualizer.getTotalSize(),
          width: "100%",
          position: "relative",
        }}
      >
        {virtualizer.getVirtualItems().map((vrow) => {
          const g = records[vrow.index];
          const aid = extractAppid(g.link) ?? "";
          const issues = recordIssues(g);
          const pct = parseReviewPercent(g.reviews);
          const reviewColor =
            pct === null
              ? "text-muted-foreground"
              : pct >= 80
                ? "text-emerald-400"
                : pct >= 70
                  ? "text-amber-400"
                  : "text-rose-400";
          return (
            <div
              key={vrow.key}
              className={cn(
                "absolute left-0 top-0 flex w-full cursor-pointer items-start gap-3 border-b border-border/50 px-3 py-2 hover:bg-accent/40",
              )}
              style={{
                transform: `translateY(${vrow.start}px)`,
                height: vrow.size,
              }}
              onClick={() => onOpen(g)}
              data-appid={aid}
            >
              {/* Thumb */}
              <div className="shrink-0">
                {g.header_image ? (
                  <img
                    loading="lazy"
                    decoding="async"
                    src={headerToCapsule(g.header_image)}
                    alt=""
                    width={80}
                    height={37}
                    className="h-10 w-20 rounded object-cover"
                    onError={(e) => {
                      // capsule_184x69 variant 404s for some games — fall
                      // back to the original header.jpg. Guard prevents an
                      // infinite loop if both URLs fail.
                      const el = e.currentTarget;
                      if (el.src !== g.header_image) el.src = g.header_image;
                    }}
                  />
                ) : (
                  <div className="h-10 w-20 rounded bg-muted" />
                )}
              </div>

              {/* Main content */}
              <div className="min-w-0 flex-1">
                <div className="flex items-start justify-between gap-2">
                  <div className="flex min-w-0 items-center gap-1 truncate text-sm font-medium">
                    {g.is_dead && <span title="Dead game">💀</span>}
                    {issues.length > 0 && (
                      <AlertTriangle
                        className="h-3 w-3 shrink-0 text-amber-400"
                        aria-label={issues.map((i) => i.label).join(" · ")}
                      />
                    )}
                    <span className="truncate">{g.name || "—"}</span>
                  </div>
                  <a
                    href={g.link}
                    target="_blank"
                    rel="noreferrer"
                    onClick={(e) => e.stopPropagation()}
                    className="shrink-0 text-muted-foreground hover:text-primary"
                    aria-label={t("edit.openOnSteam")}
                  >
                    <ExternalLink className="h-3.5 w-3.5" />
                  </a>
                </div>

                <div className="mt-1 flex flex-wrap items-center gap-1.5 text-xs">
                  {g.genre && (
                    <Badge variant="outline" className="font-normal">
                      {g.genre}
                    </Badge>
                  )}
                  {g.type_game && (
                    <Badge
                      variant={g.type_game === "online" ? "success" : "secondary"}
                      className="font-normal"
                    >
                      {g.type_game}
                    </Badge>
                  )}
                  {g.anti_cheat && g.anti_cheat !== "-" && (
                    <Badge
                      variant={g.is_kernel_ac ? "destructive" : "warning"}
                      className="font-normal"
                    >
                      {g.anti_cheat}
                    </Badge>
                  )}
                  {g.status !== "active" && (
                    <Badge variant="destructive" className="font-normal">
                      {g.status}
                    </Badge>
                  )}
                </div>

                <div className="mt-1 flex items-center gap-3 text-xs text-muted-foreground">
                  <span className={cn("font-mono", reviewColor)}>
                    {pct === null ? "—" : `${pct}%`}
                  </span>
                  <span className="font-mono">
                    {formatNumber(g.current_players)} {t("antiCheatList.players").toLowerCase()}
                  </span>
                </div>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
}

// web/src/lib/games/MobileGameCards.svelte
<script lang="ts">
  import { createVirtualizer } from "@tanstack/svelte-virtual";
  import TriangleAlert from "@lucide/svelte/icons/triangle-alert";
  import type { GameRecord } from "../schema";
  import { i18n } from "../i18n.svelte";
  import { appidOf } from "../data-store";
  import { headerToCapsule } from "../image";
  import { recordIssues } from "../validation";
  import { formatNumber, parseReviewPercent, cn } from "../utils";
  import { reviewTone } from "./columns";
  import Badge from "../ui/Badge.svelte";

  // Below md the 1,282px-wide table is unusable, so the same rows render as
  // cards. Still virtualised: 3,700 cards is as many DOM nodes as 3,700 rows.
  let { rows }: { rows: GameRecord[] } = $props();

  const t = i18n.t;
  let viewport: HTMLDivElement | undefined = $state();

  // $derived.by, and it READS `viewport` in the body.
  //
  // getScrollElement is a closure, so referencing `viewport` only inside it
  // does not register a dependency: the virtualizer was built once, before
  // bind:this had run, measured a null scroll element, and never rebuilt. The
  // symptom is subtle - getTotalSize() still returns the right height, so the
  // scrollbar looks correct, while getVirtualItems() returns nothing and every
  // row is blank.
  const virtualizer = $derived.by(() => {
    const el = viewport;
    return createVirtualizer<HTMLDivElement, HTMLDivElement>({
      count: rows.length,
      getScrollElement: () => el ?? null,
      estimateSize: () => 96,
      overscan: 8,
    });
  });

  const items = $derived($virtualizer.getVirtualItems());
</script>

<div bind:this={viewport} class="h-[calc(100dvh-18rem)] overflow-auto scrollbar-thin">
  <div style:height="{$virtualizer.getTotalSize()}px" class="relative">
    {#each items as item (item.key)}
      {@const g = rows[item.index]}
      {@const appid = appidOf(g)}
      {@const pct = parseReviewPercent(g.reviews)}
      {@const issues = recordIssues(g)}
      <a
        href={appid ? `/games/${appid}` : g.link}
        class="absolute left-0 right-0 flex gap-3 border-b px-1 py-3"
        style:height="{item.size}px"
        style:transform="translateY({item.start}px)"
      >
        {#if g.header_image}
          <img
            src={headerToCapsule(g.header_image)}
            alt=""
            loading="lazy"
            decoding="async"
            class="h-[42px] w-[90px] shrink-0 rounded object-cover"
          />
        {:else}
          <div class="h-[42px] w-[90px] shrink-0 rounded bg-muted"></div>
        {/if}

        <div class="min-w-0 flex-1">
          <div class="flex items-center gap-1.5">
            {#if g.is_dead}<span title={t("games.deadTitle")}>💀</span>{/if}
            <span class="truncate text-sm font-medium">{g.name || "—"}</span>
            {#if issues.length}
              <TriangleAlert
                class="size-3.5 shrink-0 text-warning"
                aria-label={issues.map((i) => i.label).join(" · ")}
              />
            {/if}
          </div>

          <div class="mt-1 flex flex-wrap items-center gap-1">
            {#if g.genre}<Badge variant="outline">{g.genre}</Badge>{/if}
            {#if g.type_game}
              <Badge variant={g.type_game === "online" ? "success" : "secondary"}>
                {t(g.type_game === "online" ? "common.online" : "common.offline")}
              </Badge>
            {/if}
            {#if g.anti_cheat && g.anti_cheat !== "-"}
              <Badge variant={g.is_kernel_ac ? "destructive" : "warning"}>{g.anti_cheat}</Badge>
            {/if}
          </div>
        </div>

        <div class="shrink-0 text-right">
          {#if pct !== null}
            <div class={cn("font-mono text-sm tnum", reviewTone(pct))}>{pct}%</div>
          {/if}
          <div class="font-mono text-xs text-muted-foreground tnum">
            {formatNumber(g.current_players)}
          </div>
        </div>
      </a>
    {/each}
  </div>
</div>
