// web/src/lib/common/BackToTop.svelte
<script lang="ts">
  import ArrowUp from "@lucide/svelte/icons/arrow-up";
  import { i18n } from "../i18n.svelte";
  import { cn } from "../utils";

  // The scroll container is <main>, not the window: the shell is a fixed-height
  // flex layout and the page itself never scrolls.
  let { scroller, threshold = 400 }: { scroller?: HTMLElement; threshold?: number } = $props();

  let visible = $state(false);

  $effect(() => {
    const el = scroller;
    if (!el) return;
    const onScroll = () => (visible = el.scrollTop > threshold);
    onScroll();
    // passive: this listener only reads scrollTop, and a non-passive scroll
    // listener blocks the compositor.
    el.addEventListener("scroll", onScroll, { passive: true });
    return () => el.removeEventListener("scroll", onScroll);
  });
</script>

<button
  type="button"
  aria-label={i18n.t("common.backToTop")}
  onclick={() => scroller?.scrollTo({ top: 0, behavior: "smooth" })}
  class={cn(
    "fixed bottom-4 right-4 z-20 grid size-10 place-items-center rounded-full border",
    "bg-card text-muted-foreground shadow-lg transition-all hover:text-foreground",
    visible ? "opacity-100" : "pointer-events-none translate-y-2 opacity-0",
  )}
>
  <ArrowUp class="size-4" />
</button>

// web/src/components/common/BackToTop.tsx
import { useEffect, useState, type RefObject } from "react";
import { useTranslation } from "react-i18next";
import { ArrowUp } from "lucide-react";
import { Button } from "../ui/button";
import { cn } from "../../lib/utils";

interface Props {
  /** Ref to the scroll container — listens for scrollTop changes on it. */
  scrollRef: RefObject<HTMLElement>;
  /** Pixel threshold before the button fades in. */
  threshold?: number;
}

// Floating back-to-top button anchored bottom-right of the viewport.
// Only mounts the scroll listener when scrollRef.current exists; opacity
// toggles via Tailwind transition so we don't unmount+remount on every
// scroll tick.
export function BackToTop({ scrollRef, threshold = 400 }: Props) {
  const { t } = useTranslation();
  const [visible, setVisible] = useState(false);

  useEffect(() => {
    const el = scrollRef.current;
    if (!el) return;
    const onScroll = () => setVisible(el.scrollTop > threshold);
    onScroll();
    el.addEventListener("scroll", onScroll, { passive: true });
    return () => el.removeEventListener("scroll", onScroll);
  }, [scrollRef, threshold]);

  return (
    <Button
      size="icon"
      onClick={() =>
        scrollRef.current?.scrollTo({ top: 0, behavior: "smooth" })
      }
      aria-label={t("common.backToTop")}
      title={t("common.backToTop")}
      className={cn(
        "fixed bottom-4 right-4 z-30 h-10 w-10 rounded-full shadow-lg transition-opacity duration-200",
        visible ? "opacity-100" : "pointer-events-none opacity-0",
      )}
    >
      <ArrowUp className="h-4 w-4" />
    </Button>
  );
}
