// web/src/lib/common/ConsentGate.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import ScrollText from "@lucide/svelte/icons/scroll-text";
  import ShieldCheck from "@lucide/svelte/icons/shield-check";
  import ChevronRight from "@lucide/svelte/icons/chevron-right";
  import { page } from "$app/state";
  import { consent } from "../prefs.svelte";
  import { CONSENT_DOCS, legalDocSlug } from "../legal";
  import { i18n } from "../i18n.svelte";
  import { isTauri } from "../external-open";
  import Button from "../ui/Button.svelte";

  let { children }: { children: Snippet } = $props();

  const t = i18n.t;

  let checked = $state(false);
  let declined = $state(false);

  /**
   * The error system must reach the user even before consent: a chunk-load 503
   * after a mid-session deploy, or an /error/:code deep link, would otherwise
   * be swallowed behind the gate with no way to read it.
   *
   * ANY new route that must be reachable pre-consent has to join this check.
   */
  const isErrorRoute = $derived(page.url.pathname.startsWith("/error"));
  const open = $derived(!consent.accepted && !isErrorRoute);

  async function decline() {
    // Desktop: declining means you do not get the app, so quit it. On the web
    // there is nothing to quit, so show a blocking notice with a way back.
    if (isTauri()) {
      try {
        const { getCurrentWindow } = await import("@tauri-apps/api/window");
        await getCurrentWindow().close();
        return;
      } catch (err) {
        console.error("ConsentGate: failed to close window", err);
      }
    }
    declined = true;
  }
</script>

{#if !open}
  {@render children()}
{:else if declined}
  <div class="flex min-h-dvh items-center justify-center overflow-auto p-4">
    <div class="w-full max-w-md rounded-lg border border-warning/40 bg-warning/5 p-8 text-center">
      <ShieldCheck class="mx-auto mb-4 size-10 text-warning" />
      <h1 class="mb-2 text-xl font-semibold">{t("consent.declinedTitle")}</h1>
      <p class="text-sm text-muted-foreground">{t("consent.declinedBody")}</p>
      <Button class="mt-6" variant="outline" onclick={() => (declined = false)}>
        {t("consent.back")}
      </Button>
    </div>
  </div>
{:else}
  <div class="flex min-h-dvh items-center justify-center overflow-auto p-4">
    <div class="w-full max-w-lg rounded-xl border bg-card p-6 shadow-xl sm:p-8">
      <div class="mb-5 flex items-start gap-3">
        <span class="grid size-10 shrink-0 place-items-center rounded-lg bg-primary/15 text-primary">
          <ScrollText class="size-5" />
        </span>
        <div>
          <h1 class="text-xl font-semibold">{t("consent.title")}</h1>
          <p class="mt-1 text-sm text-muted-foreground">{t("consent.intro")}</p>
        </div>
      </div>

      <p class="mb-2 text-xs font-semibold uppercase tracking-wider text-muted-foreground">
        {t("consent.docsLabel")}
      </p>
      <ul class="mb-5 space-y-1.5">
        {#each CONSENT_DOCS as doc (doc.path)}
          <li>
            <!-- Real in-app routes. These used to be links that called
                 preventDefault() and bounced to /about, because /legal/* did
                 not exist. -->
            <a
              href="/legal/{legalDocSlug(doc.path)}"
              class="flex items-center gap-2 rounded-md border bg-background px-3 py-2 text-sm
                     transition-colors hover:border-border-strong hover:bg-accent"
            >
              <span class="min-w-0 flex-1 truncate font-medium">{doc.label}</span>
              <span class="hidden truncate text-xs text-muted-foreground sm:block">{doc.hint}</span>
              <ChevronRight class="size-4 shrink-0 text-muted-foreground" />
            </a>
          </li>
        {/each}
      </ul>

      <label class="mb-5 flex cursor-pointer items-start gap-2.5 text-sm">
        <input
          type="checkbox"
          bind:checked
          class="mt-0.5 size-4 shrink-0 accent-[hsl(var(--primary))]"
        />
        <span>{t("consent.checkboxLabel")}</span>
      </label>

      <div class="flex flex-wrap gap-2">
        <Button disabled={!checked} onclick={() => consent.accept()}>
          {t("consent.continue")}
        </Button>
        <Button variant="ghost" onclick={decline}>{t("consent.decline")}</Button>
      </div>
    </div>
  </div>
{/if}

// web/src/components/common/ConsentGate.tsx
import { useState } from "react";
import { useLocation } from "react-router-dom";
import { useTranslation } from "react-i18next";
import { ScrollText, ExternalLink, ShieldCheck } from "lucide-react";
import { Button } from "../ui/button";
import { useConsent } from "../../stores/consent";
import { CONSENT_DOCS, legalDocUrl } from "../../lib/legal";
import { isTauri, openExternal } from "../../lib/external-open";

/**
 * First-run legal consent gate. Blocks the main UI until the user accepts the
 * binding documents. Kept in the EAGER bundle (no lazy import) so it paints on
 * first render with no flash — i18n is already awaited before render in
 * main.tsx. Mounted INSIDE AppErrorBoundary + the router, so a crash here is
 * caught by the top-level boundary and `useLocation` is available.
 *
 * Persistence + incognito behaviour live in stores/consent.ts.
 */
export function ConsentGate({ children }: { children: React.ReactNode }) {
  const { t } = useTranslation();
  const accepted = useConsent((s) => s.accepted);
  const accept = useConsent((s) => s.accept);
  const location = useLocation();
  const [checked, setChecked] = useState(false);
  const [declined, setDeclined] = useState(false);

  // Let the error system through even before consent: a chunk-load 503 after a
  // mid-session deploy, the GitHub Pages 404.html redirect, or an #/error/:code
  // deep link must reach the user instead of being swallowed behind the gate.
  const isErrorRoute = location.pathname.startsWith("/error");

  if (accepted || isErrorRoute) return <>{children}</>;

  function handleDecline() {
    // Desktop: declining means you don't get the app — quit it. On web there's
    // nothing to quit, so show a blocking notice with a way back to the gate.
    if (isTauri()) {
      void (async () => {
        try {
          const { getCurrentWindow } = await import("@tauri-apps/api/window");
          await getCurrentWindow().close();
        } catch (err) {
          console.error("ConsentGate: failed to close window", err);
          setDeclined(true);
        }
      })();
    } else {
      setDeclined(true);
    }
  }

  if (declined) {
    return (
      <div className="flex min-h-screen items-center justify-center overflow-auto p-4">
        <div className="w-full max-w-md rounded-lg border border-amber-500/30 bg-amber-500/5 p-8 text-center">
          <ShieldCheck className="mx-auto mb-4 h-10 w-10 text-amber-400" />
          <h1 className="mb-2 text-xl font-semibold text-foreground">
            {t("consent.declinedTitle")}
          </h1>
          <p className="text-sm text-muted-foreground">{t("consent.declinedBody")}</p>
          <div className="mt-6">
            <Button size="sm" onClick={() => setDeclined(false)}>
              {t("consent.back")}
            </Button>
          </div>
        </div>
      </div>
    );
  }

  return (
    <div className="flex min-h-screen items-center justify-center overflow-auto p-4">
      <div className="w-full max-w-lg rounded-lg border border-border bg-card p-8 text-foreground">
        <ScrollText className="mb-4 h-10 w-10 text-primary" />
        <h1 className="text-xl font-semibold">{t("consent.title")}</h1>
        <p className="mt-2 text-sm text-muted-foreground">{t("consent.intro")}</p>

        <p className="mt-5 text-xs font-medium uppercase tracking-wider text-muted-foreground">
          {t("consent.docsLabel")}
        </p>
        <ul className="mt-2 space-y-1.5">
          {CONSENT_DOCS.map((d) => (
            <li key={d.path}>
              <button
                type="button"
                onClick={() => void openExternal(legalDocUrl(d.path))}
                className="flex w-full items-center justify-between rounded-md border border-border bg-card px-3 py-2 text-left text-sm transition-colors hover:bg-accent"
              >
                <span className="font-medium">{d.label}</span>
                <ExternalLink className="h-3.5 w-3.5 shrink-0 text-muted-foreground" />
              </button>
            </li>
          ))}
        </ul>

        <label className="mt-6 flex cursor-pointer items-start gap-2.5 text-sm">
          <input
            type="checkbox"
            checked={checked}
            onChange={(e) => setChecked(e.target.checked)}
            className="mt-0.5 h-4 w-4 shrink-0 cursor-pointer accent-primary"
          />
          <span className="text-muted-foreground">{t("consent.checkboxLabel")}</span>
        </label>

        <div className="mt-6 flex flex-wrap gap-2">
          <Button disabled={!checked} onClick={() => accept()}>
            {t("consent.continue")}
          </Button>
          <Button variant="ghost" onClick={handleDecline}>
            {t("consent.decline")}
          </Button>
        </div>
      </div>
    </div>
  );
}
