// web/src/components/ui/card.tsx
import * as React from "react";
import { cn } from "../../lib/utils";

export const Card = React.forwardRef<HTMLDivElement, React.HTMLAttributes<HTMLDivElement>>(
  ({ className, ...props }, ref) => (
    <div
      ref={ref}
      className={cn(
        "rounded-lg border bg-card text-card-foreground shadow-sm",
        className,
      )}
      {...props}
    />
  ),
);
Card.displayName = "Card";

export const CardHeader = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex flex-col space-y-1.5 p-6", className)} {...props} />
));
CardHeader.displayName = "CardHeader";

export const CardTitle = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div
    ref={ref}
    className={cn("text-base font-semibold leading-none tracking-tight", className)}
    {...props}
  />
));
CardTitle.displayName = "CardTitle";

export const CardDescription = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("text-sm text-muted-foreground", className)} {...props} />
));
CardDescription.displayName = "CardDescription";

export const CardContent = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("p-6 pt-0", className)} {...props} />
));
CardContent.displayName = "CardContent";

export const CardFooter = React.forwardRef<
  HTMLDivElement,
  React.HTMLAttributes<HTMLDivElement>
>(({ className, ...props }, ref) => (
  <div ref={ref} className={cn("flex items-center p-6 pt-0", className)} {...props} />
));
CardFooter.displayName = "CardFooter";

// web/src/lib/ui/Card.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import type { HTMLAttributes } from "svelte/elements";
  import { cn } from "../utils";

  type Props = {
    class?: string;
    title?: string;
    /** Rendered before the title, e.g. an icon. */
    icon?: Snippet;
    description?: string;
    header?: Snippet;
    children: Snippet;
  } & Omit<HTMLAttributes<HTMLDivElement>, "class" | "title">;

  let { class: className, title, icon, description, header, children, ...rest }: Props =
    $props();
</script>

<div
  class={cn("rounded-lg border bg-card text-card-foreground shadow-sm", className)}
  {...rest}
>
  {#if title || header || description}
    <div class="flex flex-col space-y-1.5 p-5 pb-3">
      {#if header}
        {@render header()}
      {:else}
        <h3 class="flex items-center gap-2 text-base font-semibold leading-none tracking-tight">
          {#if icon}{@render icon()}{/if}
          {title}
        </h3>
        {#if description}
          <p class="text-sm text-muted-foreground">{description}</p>
        {/if}
      {/if}
    </div>
    <div class="p-5 pt-0">{@render children()}</div>
  {:else}
    <div class="p-5">{@render children()}</div>
  {/if}
</div>
