// web/src/routes/about/+page.svelte
<script lang="ts">
  import Mail from "@lucide/svelte/icons/mail";
  import LinkIcon from "@lucide/svelte/icons/link";
  import ExternalLink from "@lucide/svelte/icons/external-link";
  import Scale from "@lucide/svelte/icons/scale";
  import Sparkles from "@lucide/svelte/icons/sparkles";
  import TriangleAlert from "@lucide/svelte/icons/triangle-alert";
  import FileText from "@lucide/svelte/icons/file-text";
  import Bug from "@lucide/svelte/icons/bug";
  import { games } from "$lib/games.svelte";
  import { i18n } from "$lib/i18n.svelte";
  import { LEGAL_DOCS, legalDocSlug } from "$lib/legal";
  import { REPO_OWNER, REPO_NAME } from "$lib/schema";
  import { formatNumber } from "$lib/utils";
  import PageHeader from "$lib/common/PageHeader.svelte";
  import Badge from "$lib/ui/Badge.svelte";
  import Seo from "$lib/common/Seo.svelte";

  const t = i18n.t;
  const REPO_URL = `https://github.com/${REPO_OWNER}/${REPO_NAME}`;

  const total = $derived(games.data?.records.length ?? 0);
  const lastUpdated = $derived(games.data?.index.last_updated ?? "");

  // Two entries, not nine. Every other channel now lives at
  // poli0981.dev/links/, so a retired account cannot leave a dead link in a
  // shipped build - which had already happened three times.
  //
  // $derived: a plain const called t() once, at mount, so these labels stayed
  // in whatever language the page first rendered in.
  const CONTACTS = $derived([
    { icon: Mail, label: t("about.email"), handle: "contact@poli0981.dev", href: "mailto:contact@poli0981.dev" },
    { icon: LinkIcon, label: t("about.everyOtherChannel"), handle: "poli0981.dev/links", href: "https://poli0981.dev/links/" },
  ]);

  /**
   * The real stack. The React page advertised React 18, TypeScript 5, Tailwind
   * CSS 3, tailwindcss-animate, PostCSS + autoprefixer and OpenPGP.js - every
   * one of them wrong by the end, and OpenPGP.js was not even a dependency, so
   * the page credited a library that did not ship.
   */
  const DEPS = [
    { name: "Svelte 5", role: "UI runtime", href: "https://svelte.dev/", licence: "MIT" },
    { name: "SvelteKit 2", role: "routing + prerendering", href: "https://svelte.dev/docs/kit", licence: "MIT" },
    { name: "TypeScript 6", role: "type system", href: "https://www.typescriptlang.org/", licence: "Apache-2.0" },
    { name: "Vite 8 / Rolldown", role: "build", href: "https://vitejs.dev/", licence: "MIT" },
    { name: "Tailwind CSS 4", role: "styling", href: "https://tailwindcss.com/", licence: "MIT" },
    { name: "Bits UI", role: "headless UI primitives", href: "https://bits-ui.com/", licence: "MIT" },
    { name: "Apache ECharts 6", role: "charts", href: "https://echarts.apache.org/", licence: "Apache-2.0" },
    { name: "TanStack Virtual", role: "virtualised 3,600-row table", href: "https://tanstack.com/virtual", licence: "MIT" },
    { name: "Fuse.js", role: "fuzzy search", href: "https://www.fusejs.io/", licence: "Apache-2.0" },
    { name: "idb-keyval", role: "IndexedDB cache", href: "https://github.com/jakearchibald/idb-keyval", licence: "Apache-2.0" },
    { name: "unified / remark / rehype", role: "legal docs, at build time only", href: "https://unifiedjs.com/", licence: "MIT" },
    { name: "Bricolage Grotesque", role: "display typeface", href: "https://github.com/ateliertriay/bricolage", licence: "OFL-1.1" },
    { name: "IBM Plex Sans", role: "body typeface", href: "https://github.com/IBM/plex", licence: "OFL-1.1" },
    { name: "JetBrains Mono", role: "monospace typeface", href: "https://github.com/JetBrains/JetBrainsMono", licence: "OFL-1.1" },
    { name: "Tauri 2", role: "desktop + Android shell", href: "https://v2.tauri.app/", licence: "MIT or Apache-2.0" },
  ];

  const ISSUE_TEMPLATES = $derived([
    { id: "bug_report", label: t("about.tplBug"), icon: Bug },
    { id: "feature_request", label: t("about.tplFeature"), icon: Sparkles },
    { id: "delete_game", label: t("about.tplDelete"), icon: TriangleAlert },
  ]);
</script>

<Seo title={t("about.title")} description={t("about.subtitle")} />

<PageHeader title={t("about.title")} subtitle={t("about.subtitle")} />

<div class="max-w-3xl space-y-4">
  <section class="rounded-lg border bg-card p-5">
    <h2 class="text-base font-semibold">{t("about.repositoryTitle")}</h2>
    <div class="mt-3 grid gap-3 sm:grid-cols-2">
      <div class="rounded-md border bg-muted/30 p-3">
        <Badge variant="secondary">{t("about.trackedGamesLabel")}</Badge>
        <div class="mt-1 truncate font-display text-xl font-semibold tnum">{formatNumber(total)}</div>
      </div>
      <div class="rounded-md border bg-muted/30 p-3">
        <Badge variant="secondary">{t("about.dataLastUpdatedLabel")}</Badge>
        <div class="mt-1 truncate font-display text-xl font-semibold tnum">
          {lastUpdated ? lastUpdated.slice(0, 16).replace("T", " ") + "Z" : "—"}
        </div>
      </div>
    </div>
    <p class="mt-3 text-sm text-muted-foreground">{t("about.repositoryBlurb")}</p>
    <div class="mt-3 flex flex-wrap gap-2">
      <a
        href={REPO_URL}
        target="_blank"
        rel="noreferrer"
        class="inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs hover:bg-accent"
      >
        <ExternalLink class="size-3.5" /> GitHub
      </a>
      <a
        href={`${REPO_URL}/tree/main/data`}
        target="_blank"
        rel="noreferrer"
        class="inline-flex items-center gap-1.5 rounded-md border px-3 py-1.5 text-xs hover:bg-accent"
      >
        <FileText class="size-3.5" /> {t("about.rawData")}
      </a>
    </div>
  </section>

  <section class="rounded-lg border bg-card p-5">
    <h2 class="flex items-center gap-2 text-base font-semibold">
      <TriangleAlert class="size-4 text-warning" />
      {t("about.headsUpTitle")}
    </h2>
    <ul class="mt-3 list-disc space-y-2 pl-5 text-sm text-muted-foreground">
      <li>{t("about.headsUpGenre")}</li>
      <li>{t("about.headsUpEnglish")}</li>
      <li>{t("about.headsUpValve")}</li>
    </ul>
  </section>

  <section class="rounded-lg border bg-card p-5">
    <h2 class="flex items-center gap-2 text-base font-semibold">
      <Sparkles class="size-4 text-primary" />
      {t("about.aiDisclosureTitle")}
    </h2>
    <p class="mt-2 text-sm text-muted-foreground">{t("about.aiDisclosureBody")}</p>
  </section>

  <section class="rounded-lg border bg-card p-5">
    <h2 class="text-base font-semibold">{t("about.maintainerTitle")}</h2>
    <p class="mt-1 text-sm text-muted-foreground">{t("about.maintainerBlurb")}</p>
    <div class="mt-3 grid gap-2 sm:grid-cols-2">
      {#each CONTACTS as c (c.label)}
        <a
          href={c.href}
          target={c.href.startsWith("mailto:") ? undefined : "_blank"}
          rel="noreferrer"
          class="flex items-center gap-2 rounded-md border bg-background px-3 py-2 text-sm hover:bg-accent"
        >
          <c.icon class="size-4 shrink-0 text-muted-foreground" />
          <span class="min-w-0 flex-1">
            <span class="block font-medium">{c.label}</span>
            <span class="block truncate text-xs text-muted-foreground">{c.handle}</span>
          </span>
          <ExternalLink class="size-3 shrink-0 text-muted-foreground" />
        </a>
      {/each}
    </div>
  </section>

  <section class="rounded-lg border bg-card p-5">
    <h2 class="flex items-center gap-2 text-base font-semibold">
      <Bug class="size-4 text-muted-foreground" />
      {t("about.reportTitle")}
    </h2>
    <div class="mt-3 grid gap-2 sm:grid-cols-3">
      {#each ISSUE_TEMPLATES as tpl (tpl.id)}
        <a
          href={`${REPO_URL}/issues/new?template=${tpl.id}.yml`}
          target="_blank"
          rel="noreferrer"
          class="flex items-center gap-2 rounded-md border bg-background px-3 py-2 text-sm hover:bg-accent"
        >
          <tpl.icon class="size-4 shrink-0 text-muted-foreground" />
          <span class="flex-1 truncate">{tpl.label}</span>
        </a>
      {/each}
    </div>
  </section>

  <section class="rounded-lg border bg-card p-5">
    <h2 class="flex items-center gap-2 text-base font-semibold">
      <Scale class="size-4 text-muted-foreground" />
      {t("about.legalTitle")}
    </h2>
    <p class="mt-2 text-sm text-muted-foreground">{t("about.legalBlurb")}</p>
    <ul class="mt-3 space-y-1.5">
      {#each LEGAL_DOCS as doc (doc.path)}
        <li>
          <!-- Real in-app routes, rendered at build time. -->
          <a
            href="/legal/{legalDocSlug(doc.path)}"
            class="flex items-center justify-between gap-2 rounded-md border bg-background px-3 py-2 text-sm hover:bg-accent"
          >
            <span class="font-medium">{doc.label}</span>
            <span class="ml-2 hidden truncate text-xs text-muted-foreground sm:block">{doc.hint}</span>
          </a>
        </li>
      {/each}
    </ul>
  </section>

  <section class="rounded-lg border bg-card p-5">
    <h2 class="flex items-center gap-2 text-base font-semibold">
      <FileText class="size-4 text-muted-foreground" />
      {t("about.stackTitle")}
    </h2>
    <ul class="mt-3 space-y-1.5">
      {#each DEPS as d (d.name)}
        <li class="flex items-center justify-between gap-2 rounded-md border bg-background px-3 py-2 text-sm">
          <a href={d.href} target="_blank" rel="noreferrer" class="min-w-0 truncate font-medium hover:text-primary">
            {d.name}
          </a>
          <span class="hidden truncate text-xs text-muted-foreground sm:inline">{d.role}</span>
          <Badge variant="outline" class="shrink-0 font-mono">{d.licence}</Badge>
        </li>
      {/each}
    </ul>
    <p class="mt-4 border-t pt-3 text-xs text-muted-foreground">{t("about.trademarkNote")}</p>
  </section>
</div>

// web/src/pages/About.tsx
import {
  Github,
  ExternalLink,
  Heart,
  Bug,
  Lightbulb,
  Shield,
  FileText,
  MessageCircle,
  Scale,
  Sparkles,
  AlertTriangle,
  Mail,
  Link as LinkIcon,
} from "lucide-react";
import { useTranslation } from "react-i18next";
import { Card, CardContent, CardHeader, CardTitle } from "../components/ui/card";
import { Badge } from "../components/ui/badge";
import { Button } from "../components/ui/button";
import { Separator } from "../components/ui/separator";
import { useGames } from "../hooks/useGames";
import { useDocumentTitle } from "../hooks/useDocumentTitle";
import { REPO_OWNER, REPO_NAME } from "../lib/schema";
import { LEGAL_DOCS } from "../lib/legal";
import { formatNumber } from "../lib/utils";

const REPO_URL = `https://github.com/${REPO_OWNER}/${REPO_NAME}`;

interface Social {
  icon: React.ComponentType<{ className?: string }>;
  label: string;
  href: string;
  handle?: string;
}

const SOCIALS: Social[] = [
  { icon: Mail, label: "Email", handle: "contact@poli0981.dev", href: "mailto:contact@poli0981.dev" },
  { icon: LinkIcon, label: "Every other channel", handle: "poli0981.dev/links", href: "https://poli0981.dev/links/" },
];

interface Dep {
  name: string;
  role: string;
  href: string;
  /** SPDX identifier — see https://spdx.org/licenses */
  license: string;
  /** Optional direct link to the dep's LICENSE file. */
  licenseHref?: string;
}

const DEPS: Dep[] = [
  { name: "React 18", role: "UI runtime", href: "https://react.dev/", license: "MIT", licenseHref: "https://github.com/facebook/react/blob/main/LICENSE" },
  { name: "TypeScript 5", role: "type system", href: "https://www.typescriptlang.org/", license: "Apache-2.0", licenseHref: "https://github.com/microsoft/TypeScript/blob/main/LICENSE.txt" },
  { name: "Vite 8", role: "build + dev server (Rolldown)", href: "https://vitejs.dev/", license: "MIT", licenseHref: "https://github.com/vitejs/vite/blob/main/LICENSE" },
  { name: "Rolldown", role: "Rust bundler powering Vite 8", href: "https://rolldown.rs/", license: "MIT", licenseHref: "https://github.com/rolldown/rolldown/blob/main/LICENSE" },
  { name: "Tailwind CSS 3", role: "styling", href: "https://tailwindcss.com/", license: "MIT", licenseHref: "https://github.com/tailwindlabs/tailwindcss/blob/main/LICENSE" },
  { name: "Radix UI", role: "headless UI primitives", href: "https://www.radix-ui.com/", license: "MIT", licenseHref: "https://github.com/radix-ui/primitives/blob/main/LICENSE" },
  { name: "react-router-dom", role: "client-side routing", href: "https://reactrouter.com/", license: "MIT", licenseHref: "https://github.com/remix-run/react-router/blob/main/LICENSE.md" },
  { name: "TanStack Query", role: "data fetching + caching", href: "https://tanstack.com/query", license: "MIT", licenseHref: "https://github.com/TanStack/query/blob/main/LICENSE" },
  { name: "TanStack Virtual", role: "1.2k-row virtualised table", href: "https://tanstack.com/virtual", license: "MIT", licenseHref: "https://github.com/TanStack/virtual/blob/main/LICENSE" },
  { name: "Apache ECharts", role: "treemap / heatmap / wordcloud / …", href: "https://echarts.apache.org/", license: "Apache-2.0", licenseHref: "https://github.com/apache/echarts/blob/master/LICENSE" },
  { name: "echarts-for-react", role: "React binding for ECharts", href: "https://github.com/hustcc/echarts-for-react", license: "MIT", licenseHref: "https://github.com/hustcc/echarts-for-react/blob/master/LICENSE" },
  { name: "echarts-wordcloud", role: "ECharts wordcloud plugin", href: "https://github.com/ecomfe/echarts-wordcloud", license: "BSD-3-Clause", licenseHref: "https://github.com/ecomfe/echarts-wordcloud/blob/master/LICENSE" },
  { name: "OpenPGP.js", role: "client-side commit signing", href: "https://openpgpjs.org/", license: "LGPL-3.0", licenseHref: "https://github.com/openpgpjs/openpgpjs/blob/main/LICENSE" },
  { name: "Workbox + vite-plugin-pwa", role: "service worker + offline cache", href: "https://vite-pwa-org.netlify.app/", license: "MIT", licenseHref: "https://github.com/vite-pwa/vite-plugin-pwa/blob/main/LICENSE" },
  { name: "Tauri 2", role: "native desktop wrapper (shell, updater)", href: "https://v2.tauri.app/", license: "MIT or Apache-2.0", licenseHref: "https://github.com/tauri-apps/tauri/blob/dev/LICENSE_APACHE-2.0" },
  { name: "i18next", role: "i18n core engine", href: "https://www.i18next.com/", license: "MIT", licenseHref: "https://github.com/i18next/i18next/blob/master/LICENSE" },
  { name: "react-i18next", role: "React bindings for i18next", href: "https://react.i18next.com/", license: "MIT", licenseHref: "https://github.com/i18next/react-i18next/blob/master/LICENSE" },
  { name: "i18next-browser-languagedetector", role: "auto-detect locale", href: "https://github.com/i18next/i18next-browser-languageDetector", license: "MIT", licenseHref: "https://github.com/i18next/i18next-browser-languageDetector/blob/master/LICENSE" },
  { name: "Zustand", role: "UI/state store", href: "https://zustand-demo.pmnd.rs/", license: "MIT", licenseHref: "https://github.com/pmndrs/zustand/blob/main/LICENSE" },
  { name: "Fuse.js", role: "fuzzy search", href: "https://www.fusejs.io/", license: "Apache-2.0", licenseHref: "https://github.com/krisk/Fuse/blob/main/LICENSE" },
  { name: "cmdk", role: "command palette", href: "https://cmdk.paco.me/", license: "MIT", licenseHref: "https://github.com/pacocoursey/cmdk/blob/main/LICENSE" },
  { name: "lucide-react", role: "icons", href: "https://lucide.dev/", license: "ISC", licenseHref: "https://github.com/lucide-icons/lucide/blob/main/LICENSE" },
  { name: "sonner", role: "toasts", href: "https://sonner.emilkowal.ski/", license: "MIT", licenseHref: "https://github.com/emilkowalski/sonner/blob/main/LICENSE.md" },
  { name: "idb-keyval", role: "IndexedDB wrapper", href: "https://github.com/jakearchibald/idb-keyval", license: "Apache-2.0", licenseHref: "https://github.com/jakearchibald/idb-keyval/blob/main/LICENSE" },
  { name: "class-variance-authority", role: "component variant API", href: "https://cva.style/", license: "Apache-2.0", licenseHref: "https://github.com/joe-bell/cva/blob/main/LICENSE" },
  { name: "clsx", role: "conditional className join", href: "https://github.com/lukeed/clsx", license: "MIT", licenseHref: "https://github.com/lukeed/clsx/blob/master/license" },
  { name: "tailwind-merge", role: "Tailwind class merging", href: "https://github.com/dcastil/tailwind-merge", license: "MIT", licenseHref: "https://github.com/dcastil/tailwind-merge/blob/main/LICENSE.md" },
  { name: "tailwindcss-animate", role: "animation utilities for Tailwind", href: "https://github.com/jamiebuilds/tailwindcss-animate", license: "MIT", licenseHref: "https://github.com/jamiebuilds/tailwindcss-animate/blob/main/LICENSE" },
  { name: "PostCSS + autoprefixer", role: "CSS post-processing (build-only)", href: "https://postcss.org/", license: "MIT", licenseHref: "https://github.com/postcss/postcss/blob/main/LICENSE" },
];

const ISSUE_TEMPLATES = [
  { id: "bug_report", label: "Bug report", icon: Bug, color: "text-rose-400" },
  { id: "feature_request", label: "Feature request", icon: Lightbulb, color: "text-amber-400" },
  { id: "delete_game", label: "Delete game", icon: Shield, color: "text-violet-400" },
  { id: "feedback", label: "Feedback", icon: MessageCircle, color: "text-blue-400" },
];

export function AboutPage() {
  const { t } = useTranslation();
  useDocumentTitle("about.title");
  const games = useGames();
  const total = games.data?.records.length ?? 0;
  const lastUpdated = games.data?.index.last_updated ?? "";

  return (
    <div className="max-w-3xl space-y-6">
      <div>
        <h1 className="text-2xl font-semibold tracking-tight">{t("about.title")}</h1>
        <p className="text-sm text-muted-foreground">{t("about.subtitle")}</p>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Github className="h-4 w-4" /> {t("about.repositoryTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid gap-3 sm:grid-cols-2">
            <Stat label={t("about.trackedGamesLabel")} value={formatNumber(total)} />
            <Stat
              label={t("about.dataLastUpdatedLabel")}
              value={lastUpdated ? lastUpdated.slice(0, 16).replace("T", " ") + "Z" : "—"}
            />
          </div>
          <p className="text-sm text-muted-foreground">
            <strong>{REPO_OWNER}/{REPO_NAME}</strong> — a curated, automatically
            refreshed list of free-to-play Steam games. Daily Python pipeline +
            GitHub Actions; this web app sits on top of the same data shards.
            Code is MIT; the dataset is CC BY 4.0.
          </p>
          <div className="flex flex-wrap gap-2">
            <Button asChild variant="outline" size="sm">
              <a href={REPO_URL} target="_blank" rel="noreferrer">
                <Github className="mr-1 h-3 w-3" /> GitHub
              </a>
            </Button>
            <Button asChild variant="outline" size="sm">
              <a href={`${REPO_URL}/tree/main/data`} target="_blank" rel="noreferrer">
                <FileText className="mr-1 h-3 w-3" /> Raw data (JSONL)
              </a>
            </Button>
            <Button asChild variant="outline" size="sm">
              <a href={`${REPO_URL}/blob/main/games/top-online.md`} target="_blank" rel="noreferrer">
                <ExternalLink className="mr-1 h-3 w-3" /> Top online (markdown)
              </a>
            </Button>
            <Button asChild variant="outline" size="sm">
              <a
                href={`https://raw.githubusercontent.com/${REPO_OWNER}/${REPO_NAME}/main/data/data_001.jsonl`}
                target="_blank"
                rel="noreferrer"
              >
                <ExternalLink className="mr-1 h-3 w-3" /> Raw JSONL (shard 1)
              </a>
            </Button>
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <AlertTriangle className="h-4 w-4 text-amber-400" /> {t("about.headsUpTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-muted-foreground">
          <ul className="list-disc space-y-1.5 pl-5">
            <li>
              <strong>Genre is best-effort.</strong> The pipeline picks one genre
              per game by reading Steam tags and parsing the description; for
              hybrids and weird indie titles it can be wrong. The
              <em> Edit </em> drawer lets the maintainer fix it manually.
            </li>
            <li>
              <strong>English-language assumption.</strong> The scraper, ingest
              pipeline, and this UI all assume Steam pages and search results
              are in English. Steam regional storefront overrides can break
              parsing — names / genres / DLC counts may end up incorrect for
              non-EN users.
            </li>
            <li>
              <strong>Test data may have leaked in.</strong> While building the
              app, a handful of records were committed as part of testing
              (edits, adds, deletes). They eventually get cleaned up by the
              daily pipeline, but if you spot a row that looks off, file a
              <em> Bug Report</em> issue.
            </li>
            <li>
              <strong>"Unsigned" commits in the activity feed are mine.</strong>{" "}
              Many of those are commits I made while the GPG key wasn't unlocked
              during development; they're not malicious — just a lock-state
              artefact, not signed.
            </li>
            <li>
              <strong>This is not a Valve / Steam product.</strong> Independent
              project, no affiliation, no support contract.
            </li>
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Sparkles className="h-4 w-4 text-violet-400" /> {t("about.aiDisclosureTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-2 text-sm text-muted-foreground">
          <p>
            About <strong>~70 %</strong> of the code in this repository was
            generated with the help of large-language-model assistants:
          </p>
          <ul className="list-disc space-y-1 pl-5">
            <li>
              <strong>Grok</strong> — initial v1 Python pipeline (~2025).
            </li>
            <li>
              <strong>Claude</strong> — v2 refactor, the Python data layer, this
              entire web app, the GPG signing path, the legal docs you're
              reading, and most of the recent commits.
            </li>
          </ul>
          <p>
            Generated code is reviewed and tested before each commit, but
            mistakes happen — especially in subtle areas like commit-bytes
            formatting (which we got wrong twice before fixing in 4.1) and
            CDN-cache invalidation (fixed in 6.2). Please file an issue if you
            see something off.
          </p>
          <p>
            No user data is sent to any LLM at runtime. The only AI calls
            happen on my dev machine while I'm writing code, never from your
            browser.
          </p>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Heart className="h-4 w-4 text-rose-400" /> {t("about.maintainerTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            One Vietnamese dev (poli0981 / SkullMute), running this in spare
            time. Hit me up on any of these if something is broken or you want
            to chat:
          </p>
          <div className="grid gap-2 sm:grid-cols-2">
            {SOCIALS.map((s) => (
              <a
                key={s.label}
                href={s.href}
                target={s.href.startsWith("mailto:") ? undefined : "_blank"}
                rel="noreferrer"
                className="flex items-center gap-2 rounded-md border bg-card px-3 py-2 text-sm transition-colors hover:bg-accent"
              >
                <s.icon className="h-4 w-4 text-muted-foreground" />
                <div className="flex-1 min-w-0">
                  <div className="font-medium">{s.label}</div>
                  {s.handle && (
                    <div className="truncate text-xs text-muted-foreground">{s.handle}</div>
                  )}
                </div>
                <ExternalLink className="h-3 w-3 text-muted-foreground" />
              </a>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Bug className="h-4 w-4" /> {t("about.reportTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            Issue templates pre-fill labels and required fields so I can triage
            faster.
          </p>
          <div className="grid gap-2 sm:grid-cols-2">
            {ISSUE_TEMPLATES.map((t) => (
              <a
                key={t.id}
                href={`${REPO_URL}/issues/new?template=${t.id}.yml`}
                target="_blank"
                rel="noreferrer"
                className="flex items-center gap-2 rounded-md border bg-card px-3 py-2 text-sm transition-colors hover:bg-accent"
              >
                <t.icon className={"h-4 w-4 " + t.color} />
                <span className="flex-1 font-medium">{t.label}</span>
                <ExternalLink className="h-3 w-3 text-muted-foreground" />
              </a>
            ))}
          </div>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <Scale className="h-4 w-4" /> {t("about.legalTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            Code, docs and this web app are{" "}
            <a
              href={`${REPO_URL}/blob/main/LICENSE`}
              target="_blank"
              rel="noreferrer"
              className="text-primary hover:underline"
            >
              MIT-licensed
            </a>
            . The <strong>dataset</strong> (<code>data/**</code>,{" "}
            <code>games/**</code>) is licensed separately under{" "}
            <a
              href={`${REPO_URL}/blob/main/LICENSE-DATA`}
              target="_blank"
              rel="noreferrer"
              className="text-primary hover:underline"
            >
              CC BY 4.0
            </a>
            . Everything below is supplemental — those two licences still
            govern.
          </p>
          <ul className="space-y-1.5">
            {LEGAL_DOCS.map((d) => (
              <li
                key={d.path}
                className="flex items-center justify-between rounded-md border bg-card px-3 py-2 text-sm"
              >
                <a
                  href={`${REPO_URL}/blob/main/${d.path}`}
                  target="_blank"
                  rel="noreferrer"
                  className="font-medium hover:text-primary"
                >
                  {d.label}
                </a>
                <span className="ml-2 truncate text-xs text-muted-foreground">
                  {d.hint}
                </span>
              </li>
            ))}
          </ul>
        </CardContent>
      </Card>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2">
            <FileText className="h-4 w-4" /> {t("about.stackTitle")}
          </CardTitle>
        </CardHeader>
        <CardContent className="space-y-3">
          <p className="text-sm text-muted-foreground">
            All third-party libraries used by this app, with their SPDX licence
            identifiers. The Python pipeline relies on <code>requests</code> +{" "}
            <code>urllib3</code> only (both Apache-2.0).
          </p>
          <ul className="space-y-1.5">
            {DEPS.map((d) => (
              <li
                key={d.name}
                className="flex items-center justify-between gap-2 rounded-md border bg-card px-3 py-2 text-sm"
              >
                <a
                  href={d.href}
                  target="_blank"
                  rel="noreferrer"
                  className="min-w-0 truncate font-medium hover:text-primary"
                >
                  {d.name}
                </a>
                <span className="hidden truncate text-xs text-muted-foreground sm:inline">
                  {d.role}
                </span>
                {d.licenseHref ? (
                  <a
                    href={d.licenseHref}
                    target="_blank"
                    rel="noreferrer"
                    className="shrink-0"
                    title={`${d.license} licence`}
                  >
                    <Badge variant="outline" className="font-mono">
                      {d.license}
                    </Badge>
                  </a>
                ) : (
                  <Badge variant="outline" className="shrink-0 font-mono">
                    {d.license}
                  </Badge>
                )}
              </li>
            ))}
          </ul>
          <Separator />
          <div className="text-xs text-muted-foreground">
            Steam, Steam Store, Steam Community, and the Steam logo are
            trademarks of Valve Corporation. This site is not affiliated with
            Valve.
            <br />
            Everything on this site is served from this site, which fetches it
            from GitHub and Valve&apos;s CDN server-side — your browser contacts
            neither. That now includes the Activity page, which used to call{" "}
            <code>api.github.com</code> and load avatars from GitHub directly.
            See the Privacy Policy for the full picture.
          </div>
        </CardContent>
      </Card>
    </div>
  );
}

function Stat({ label, value }: { label: string; value: string }) {
  return (
    <div className="rounded-md border bg-muted/30 p-3">
      <Badge variant="secondary">{label}</Badge>
      <div className="mt-1 truncate text-xl font-semibold">{value}</div>
    </div>
  );
}
