// web/src/lib/layout/Sidebar.svelte
<script lang="ts">
  import { page } from "$app/state";
  import { PRIMARY, SECONDARY, isActive } from "../nav";
  import { i18n } from "../i18n.svelte";
  import { cn } from "../utils";
  import Gamepad from "@lucide/svelte/icons/gamepad-2";

  let { onNavigate }: { onNavigate?: () => void } = $props();

  const t = i18n.t;
</script>

<div class="flex h-full flex-col gap-1 overflow-y-auto scrollbar-thin px-3 py-4">
  <a
    href="/"
    onclick={onNavigate}
    class="mb-4 flex items-center gap-2.5 px-2 focus-visible:rounded-md"
  >
    <span class="grid size-8 place-items-center rounded-lg bg-primary text-primary-foreground">
      <Gamepad class="size-4" />
    </span>
    <span class="min-w-0">
      <span class="block truncate font-display text-[15px] font-semibold leading-tight">
        F2P Tracker
      </span>
      <!-- Derived, not hardcoded. The old rail said "Steam · v1.0" while
           package.json was at 1.4.5 — a literal that nothing updated. -->
      <span class="block truncate text-[11px] leading-tight text-muted-foreground tnum">
        Steam · v{__APP_VERSION__}
      </span>
    </span>
  </a>

  <nav aria-label={t("nav.primary")} class="flex flex-col gap-0.5">
    {#each PRIMARY as item (item.to)}
      {@const active = isActive(page.url.pathname, item)}
      <a
        href={item.to}
        onclick={onNavigate}
        aria-current={active ? "page" : undefined}
        class={cn(
          "flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm font-medium transition-colors",
          active
            ? "bg-primary/12 text-primary"
            : "text-muted-foreground hover:bg-accent hover:text-foreground",
        )}
      >
        <item.icon class="size-4 shrink-0" />
        <span class="truncate">{t(item.i18n)}</span>
      </a>
    {/each}
  </nav>

  <div class="mt-6 px-2.5 pb-1 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
    {t("nav.manage")}
  </div>

  <nav aria-label={t("nav.secondary")} class="flex flex-col gap-0.5">
    {#each SECONDARY as item (item.to)}
      {@const active = isActive(page.url.pathname, item)}
      <a
        href={item.to}
        onclick={onNavigate}
        aria-current={active ? "page" : undefined}
        class={cn(
          "flex items-center gap-2.5 rounded-md px-2.5 py-2 text-sm font-medium transition-colors",
          active
            ? "bg-primary/12 text-primary"
            : "text-muted-foreground hover:bg-accent hover:text-foreground",
        )}
      >
        <item.icon class="size-4 shrink-0" />
        <span class="truncate">{t(item.i18n)}</span>
      </a>
    {/each}
  </nav>

  <div class="mt-auto px-2.5 pt-4">
    <a
      href="https://github.com/poli0981/free-steam-games-list"
      target="_blank"
      rel="noreferrer"
      class="text-xs text-muted-foreground underline-offset-2 hover:text-foreground hover:underline"
    >
      {t("nav.sourceOnGitHub")}
    </a>
  </div>
</div>

// web/src/components/layout/Sidebar.tsx
import { NavLink } from "react-router-dom";
import {
  LayoutDashboard,
  Gamepad2,
  Trophy,
  HeartPulse,
  PlusCircle,
  Settings,
  BarChart3,
  PieChart,
  Globe,
  Tags as TagsIcon,
  Shield,
} from "lucide-react";
import { cn } from "../../lib/utils";

interface NavItem {
  to: string;
  label: string;
  icon: React.ComponentType<{ className?: string }>;
  end?: boolean;
}

const PRIMARY: NavItem[] = [
  { to: "/", label: "Dashboard", icon: LayoutDashboard, end: true },
  { to: "/games", label: "Games", icon: Gamepad2 },
  { to: "/top-online", label: "Top Online", icon: Trophy },
];

const CHARTS: NavItem[] = [
  { to: "/charts/genres", label: "Genres", icon: PieChart },
  { to: "/charts/platforms", label: "Platforms", icon: Globe },
  { to: "/charts/tags", label: "Tags", icon: TagsIcon },
  { to: "/charts/anti-cheat", label: "Anti-Cheat", icon: Shield },
  { to: "/charts/reviews", label: "Reviews", icon: BarChart3 },
];

const SECONDARY: NavItem[] = [
  { to: "/health", label: "Health", icon: HeartPulse },
  { to: "/add", label: "Add", icon: PlusCircle },
  { to: "/settings", label: "Settings", icon: Settings },
];

function Item({ item }: { item: NavItem }) {
  return (
    <NavLink
      to={item.to}
      end={item.end}
      className={({ isActive }) =>
        cn(
          "flex items-center gap-2 rounded-md px-3 py-2 text-sm font-medium transition-colors",
          isActive
            ? "bg-primary/15 text-primary"
            : "text-muted-foreground hover:bg-accent hover:text-foreground",
        )
      }
    >
      <item.icon className="h-4 w-4" />
      {item.label}
    </NavLink>
  );
}

export function Sidebar() {
  return (
    <aside className="hidden w-60 shrink-0 border-r bg-card/40 lg:flex lg:flex-col">
      <div className="flex h-14 items-center gap-2 border-b px-4">
        <div className="grid h-8 w-8 place-items-center rounded-md bg-primary/15 text-primary">
          <Gamepad2 className="h-4 w-4" />
        </div>
        <div className="flex flex-col leading-tight">
          <span className="text-sm font-semibold">F2P Tracker</span>
          <span className="text-xs text-muted-foreground">Steam · v0.1</span>
        </div>
      </div>

      <nav className="flex-1 space-y-6 overflow-y-auto px-2 py-4">
        <div className="space-y-1">
          {PRIMARY.map((i) => (
            <Item key={i.to} item={i} />
          ))}
        </div>

        <div>
          <div className="px-3 pb-1 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
            Charts
          </div>
          <div className="space-y-1">
            {CHARTS.map((i) => (
              <Item key={i.to} item={i} />
            ))}
          </div>
        </div>

        <div>
          <div className="px-3 pb-1 text-[11px] font-semibold uppercase tracking-wider text-muted-foreground">
            Manage
          </div>
          <div className="space-y-1">
            {SECONDARY.map((i) => (
              <Item key={i.to} item={i} />
            ))}
          </div>
        </div>
      </nav>

      <div className="border-t px-4 py-3 text-xs text-muted-foreground">
        <a
          href="https://github.com/poli0981/free-steam-games-list"
          target="_blank"
          rel="noreferrer"
          className="hover:text-foreground"
        >
          poli0981 / free-steam-games-list
        </a>
      </div>
    </aside>
  );
}
